### 1. Qwen plus 3.6

In [ ]:
from openai import OpenAI
api_key = 'xxxxxxxx' # Replace 'xxxxxxxx' with your actual OpenAI API key

In [2]:
import pandas as pd
import os
for i in range(1, 2):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
text

Start to analyze paper001

"# Preparation of Poly(amide-imide)s Derived from Biphenyltetracarboxylic Dianhydrides\n\nAKINORI SHIOTANI, $ ^{1} $  MASAFUMI KOHDA $ ^{1} $\n\n¹Chiba Research Laboratory, UBE Industries Ltd., 8-1 Goi-Minamikaigan, Ichihara city, CHIBA, 290 Japan\n\nReceived 25 April 1996; accepted 25 April 1996\n\nABSTRACT: Four new diimide-dicarboxylic acids (I–IV) were prepared by condensation of s- or a-BPDA with para- or meta-aminobenzoic acid. A series of aromatic poly(amideimide)s containing these diimide-dicarboxylic units was prepared by three methods: (1) acid chloride method, (2) triphenylphosphite method, and (3) one-pot method. A typical polymer of the series is readily soluble in polar aprotic solvents such as N-methyl-2-pyrrolidone (NMP), dimethylsulfoxide (DMSO), and pyridine (py) and could be cast into tough and flexible films. These were characterized by inherent viscosity, differential scanning calorimetry (DSC), and thermogravimetric analysis (TGA) measurements. The glass transition temperatures of these polymers were in the range of 220–290°C, and the 5% weight loss temperatures were 450–500°C. Films prepared by casting from polymer solutions exhibited good tensile properties. © 1997 John Wiley & Sons, Inc. J Appl Polym Sci 63: 865–873, 1997\n\nKey words: poly(amide-imide)s; 3,3',4,4'-biphenyltetracarboxylic dianhydride; 2,3,3',4'-biphenyltetracarboxylic dianhydride; p-aminobenzoic acid; m-aminobenzoic acid; polycondensation\n\n# INTRODUCTION\n\nAromatic polyimides (PIs) are well known as high-temperature, resistant materials and have been widely used in aerospace and microelectronics industries. $ ^{1,2} $  Kapton $ ^{\\circledR} $  (poly(4,4'-oxydiphenylene pyromellitimide) has been commercialized by DuPont Co. in the 1960s. We have developed a method of production for biphenyltetracarboxylic dianhydride (BPDA) $ ^{3,4} $  and put a new polyimide Upilex $ ^{\\circledR} $  on the market in 1982. Wholly aromatic polyimides are absolutely infusible; thus, the two-step process is generally utilized for the production of polyimides. Aromatic poly(amide-imide) (PAIs) are more readily processed by the injection molding or extrusion technique. PAIs are important engineering plastics due to their excellent mechanical properties, high thermal stability, and improved processability, in particular, as\n\ncompared with PIs. A number of PAIs have been previously described: (1) PAI from trimellitic anhydride with diamines, $ ^{6} $  (2) PAI from monoimide-dicarboxylic acids with diamines, $ ^{7-9} $  (3) PAI from diimide-dicarboxylic acids with diamines, $ ^{10-27} $  (4) PAI from diimide-diamines with dicarboxylic acids, $ ^{28} $  and (5) PAI by the Pd-catalyzed carbonylation of aromatic dihalides containing an imide-skeleton with diamines. $ ^{29,30} $\n\nIn this contribution, we wish to report the preparation of new diimide-dicarboxylic acids derived from BPDA and a number of PAIs therefrom.\n\n# EXPERIMENTAL\n\n# Materials\n\n3,3',4,4'-biphenyltetracarboxylic dianhydride (s-BPDA) and 2,3,3',4'-biphenyltetracarboxylic dianhydride (a-BPDA) are products of UBE Industries Ltd. Other chemicals were commercially available. Aromatic diamines used were\n\n$  \\text{H}_2\\text{N-Ar-NH}_2 =  $\n\na (BAPS)\n\n***Nc1ccc(Oc2ccc(S(=O)(=O)c3ccc(Oc4ccc(N)cc4)cc3)cc2)cc1***\n\nb (BAPS-M)\n\n***Nc1cccc(Oc2ccc(S(=O)(=O)c3ccc(Oc4cccc(N)c4)cc3)cc2)c1***\n\nc (BAPB)\n\n***Nc1ccc(Oc2ccc(-c3ccc(Oc4ccc(N)cc4)cc3)cc2)cc1***\n\nd (BAPE)\n\n***Nc1ccc(Oc2ccc(Oc3ccc(Oc4ccc(N)cc4)cc3)cc2)cc1***\n\ne (BAPP)\n\n***CC(C)(c1ccc(Oc2ccc(N)cc2)cc1)c1ccc(Oc2ccc(N)cc2)cc1***\n\nf (TPE-Q)\n\n***Nc1ccc(Oc2ccc(Oc3ccc(N)cc3)cc2)cc1***\n\ng (TPE-R)\n\n***Nc1ccc(Oc2cccc(Oc3ccc(N)cc3)c2)cc1***\n\nh (DADE)\n\n***Nc1ccc(Oc2ccc(N)cc2)cc1***\n\ni (3,3'-DADS)\n\n***Nc1cccc(S(=O)(=O)c2cccc(N)c2)c1***\n\nj (PPD)\n\n***Nc1ccc(N)cc1***\n\nFigure 1 Diamines used in the polycondensation.\n\nbis[4-(4-aminophenoxy)phenyl]sulfone (BAPS), bis[4-(3-aminophenoxy)phenyl]sulfone (BAPS-M), 4,4'-bis(4-aminophenoxy)biphenyl (BAPB), 4,4'-bis(4-aminophenoxy)biphenylether (BAPE), 2,2-bis(4-aminophenoxy)benzene (TPE-Q), 1,3-bis(4-aminophenoxy)benzene (TPE-R), 4,4'-diaminodiphenylether (DADE), 3,3'-diaminodiphenylsulfone (3,3'-DADS), and p-phenylenediamine (PPD). These diamines, as shown by their formulae in Figure 1, were used without further purification. N-Methyl-2-pyrrolidone (NMP) was purified by distillation under reduced pressure. Pyridine (py), thionyl chloride, and toluene were distilled prior to use.\n\nDiimide-dicarboxylic acids (DIDAs) were prepared by condensation of s- or a-BPDA with para- or meta-aminobenzoic acid under nitrogen. The synthesis of N,N'-bis(4-carboxyphenyl)-biphenyl-3,3',4,4'-tetracarboxydiimide (I) serves to illustrate the method. The reaction vessel was a 500 mL three-necked round flask equipped with a mechanical stirrer, a water separating trap topped by a condenser, and a nitrogen inlet. In a typical experiment, p-amino-benzoic acid (27.43 g, 0.20M) in 300 mL of NMP was combined with s-BPDA (29.42 g, 0.10M) at room temperature. The mixture was heated to 100°C to afford a homogeneous solution within 0.5 h. 50 mL of toluene was added, and the reaction was completed under reflux for 4 h, removing the water azeotropically. After the first 40 minutes, a light yellow product began to precipitate from the reaction mixture. On standing overnight at room temperature, the product was filtered, washed with 500 mL of acetone, and dried in vacuum at 120°C for 3 h.\n\nyield of I was 50.61 g (95%); mp = 444°C (by DSC). IR (KBr disc.) was 1778 (imide C=O), 1732 (imide C=O), 1373 (imide ring C—N), and 754 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. calcd: for C₃₀H₁₆N₂O₈ was as follows: C, 67.67; H, 3.03; N, 5.26. Found was as follows: C, 67.9; H, 3.3; N, 5.3. N,N'-bis(3-carboxyphenyl)-biphenyl-3,3',4,4'-tetracarboxydiimide (II), N,N'-bis(4-carboxyphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (III), and N,N'-bis(3-carboxyphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (IV) were prepared accordingly.\n\nII: yield was 91%; mp = 426°C (by DSC). IR (KBr disc.) was 1776 (imide C=O), 1730 and 1722 (imide C=O), 1379 (imide ring C—N), and 758 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. found: C, 67.9; H, 3.3; N, 5.3.\n\nIII: yield was 88%; mp = 414°C (by DSC). IR (KBr disc.): 1776 (imide C=O), 1720 (imide C=O), 1375 (imide ring C—N), and 762 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. found: C, 67.2; H, 2.8; N, 5.2.\n\nIV: yield was 80%; mp = 423°C (by DSC). IR (KBr disc.): 1768 (imide C=O), 1716 (imide C=O), 1375 (imide ring C—N), and 754 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. found: C, 67.2; H, 2.8; N, 5.1. Diimide-dicarboxylic acid dichlorides (DIDA-Cl) were synthesized by the chlorination of DIDA with excess thionyl chloride. As a typical procedure, the synthesis of N,N'-bis(4-chlorocarbonylphenyl)-biphenyl-3,3',4,4'-tetra-carboxydiimide (I-Cl) is given as follows: In a 300 mL round flask, a mixture of I (5.00 g), thionyl chloride (150 mL), and three drops of dimethylformamide as a catalyst was heated under reflux for 6 h. On standing overnight, thionyl chloride\n\nwas distilled off; and the product was washed two times with 30 mL of dry toluene, filtered, and dried in vacuum at 80°C for 6 h. Yield was 5.23 g (98%). Anal. calcd. for C₃₀H₁₄N₂O₆Cl₂: C, 63.29; H, 2.45; N, 4.92; Cl, 12.45. Found: C, 63.4; H, 2.5; N, 4.9; Cl, 12.6. N,N'-bis(3-chlorocarbonylphenyl)-biphenyl-3,3',4,4'-tetracarboxydiimide (II-Cl), N,N'-bis(4-chlorocarbonylphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (III-Cl), and N,N'-bis(3-chlorocarbonylphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (IV-Cl) were prepared accordingly.\n\nII-Cl: yield was 99%. Anal. found: C, 63.3; H, 2.5; N, 4.9; Cl, 12.5. III-Cl: yield was 99%, Anal. found: C, 63.5; H, 2.6; N, 4.8; Cl, 12.6. IV-Cl: yield was 98%, Anal. found: C, 62.3; H, 2.6; N, 5.0; Cl, 12.6.\n\n# Polycondensation\n\n# Acid Chloride Method\n\nAs a typical experiment, the polycondensation of II-Cl with BAPS under nitrogen was conducted as follows. In a 100 mL four-necked round flask equipped with a mechanical stirrer, a condenser, a dropping funnel, and a nitrogen inlet were combined II-Cl (1.423 g, 2.5mM), NMP (15 mL), and pyridine (0.5 mL). A solution containing BAPS (1.081 g, 2.5mM) and NMP (5 mL) was added through a funnel into the reaction mixture at 60°C within 15 min. The funnel was washed with an additional 3 mL of NMP. After several minutes, a polymerization started, and the reaction temperature was maintained at 60°C for 100 min in an oil bath. The resulting viscous solution was poured into 1 L of water under rapid stirring, and the product precipitated was pulverized with a cooking mixer. The product was washed with 0.5 L of water and 0.5 L of methanol and dried in vacuum at 120°C for 3 h. Yield was 2.219 g (96%).\n\n# Triphenyl Phosphate Method\n\nAs a typical procedure, the polycondensation of IV with TPE-Q is described. Using the identical equipment IV (1.331 g, 2.5mM), TPE-Q (0.731 g, 2.5mM), CaCl₂ (1.2 g), NMP (20 mL), pyridine (4 mL), and P(OPh)₃ (1.5 mL) were combined. The reaction mixture was heated to 150°C to afford a clear solution within 5 min. The reaction temperature was maintained at 150°C for 3 h. The resulting viscous solution was treated as aforementioned. Yield was 1.873 g (95%).\n\n# One-Pot Method\n\nAs a typical example, the polycondensation of s-BPDA and m-ABA with DADE is given. In a 100\n\nmL three-necked round flask, m-aminobenzoic acid (0.686 g, 5.0 mM) in 7 mL of anhydrous NMP under nitrogen was combined with s-BPDA (0.736 g, 2.5 mM) at room temperature. The mixture was heated to 100°C to afford a homogeneous solution within 0.5 h. Addition of 6 mL of toluene after 20 min induced precipitation of a light yellow product. To remove water azeotropically, the reaction mixture was kept under reflux for 4 h. After cooling to room temperature and removing the water separating trap, DADE (0.511 g, 2.55 mM), CaCl₂ (1.2 g), NMP (14 mL), pyridine (4 mL), and P(OPh)₃ (1.5 mL) were added to the mixture, which was heated to 150°C to afford a clear solution within 5 min. After 3 h, at 150°C, a viscous solution resulted, which was treated as aforementioned. Yield was 1.707 g (98%).\n\n# Measurements\n\nThe films used for the thermal measurements were prepared by casting NMP solutions containing 20% polymer by weight onto a glass plate and drying at 80°C for 30 min, 80–170°C for 30 min, 200°C for 30 min, 200–300°C for 15 min, and 300°C for 30 min.\n\nDifferential scanning calorimetry (DSC) measurements were conducted on a Seiko-Denshi DS2000 instrument in aluminium pans at a heating rate of 20°C/min under nitrogen. Glass transition temperatures ( $ T_g $ s) were determined from the DSC curves.  $ T_g $ s of polymers VII (Table IV) could not be unambiguously determined from the DSC measurements. Thermogravimetric measurements (TGA) were conducted at a heating rate of 10°C/min under nitrogen. The 5% weight loss temperatures ( $ T_d^5 $ s) were determined from the TGA curve. Inherent viscosities were measured with a Cannon Fenske viscosimeter in NMP solution (0.5 g/dL, 30°C). Infrared spectra were recorded on a Nihondenshi JIR-5500 Fourier transform infrared (FTIR) spectrometer. Test pieces (6 cm long, 0.4 mm wide, and 0.02 mm thick) for mechanical measurements were prepared by a casting method, as described above, and the tensile data were obtained according to the ASTM D882 standard.\n\n# RESULTS AND DISCUSSION\n\n# Monomer Synthesis\n\nFour novel diimide-dicarboxylic acids (I–IV) have been prepared by condensation of s- or a-\n\nTable I Conditions for the Acid Chloride Method and Inherent Viscosities of PAIs $ ^{a} $\n\n| Polymer   | DIDA   | Diamine   | Polycondensation   | Polycondensation   | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n|:----------|:-------|:----------|:-------------------|:-------------------|:------------|:------------------------------------------|\n| Polymer   | DIDA   | Diamine   | Temp. (°C)         | Time (min)         | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n| Va        | I      | a         | 70                 | 95                 | 97          | 1.34                                      |\n| Vb        |        | b         | 70                 | 105                | 93          | 1.35                                      |\n| Ve        |        | e         | 70                 | 180                | 95          | 1.64                                      |\n| Vi        |        | i         | 70                 | 60                 | 90          | 1.17                                      |\n| VIa       | II     | a         | 60                 | 100                | 91          | 0.83                                      |\n| VIc       |        | c         | 60                 | 65                 | 82          | 0.84                                      |\n| VId       |        | d         | 60                 | 65                 | 84          | 0.73                                      |\n| VIe       |        | e         | 60                 | 180                | 92          | 0.50                                      |\n| VIf       |        | f         | 60                 | 65                 | 86          | 1.04                                      |\n| VIg       |        | g         | 60                 | 180                | 94          | 0.81                                      |\n| VIh       |        | h         | 80                 | 180                | 94          | 0.89                                      |\n| VIi       |        | i         | 60                 | 80                 | 89          | 0.36                                      |\n| VIIa      | III    | a         | 65                 | 90                 | 84          | 1.17                                      |\n| VIIb      |        | b         | 60                 | 100                | 90          | 0.99                                      |\n| VIIc      |        | c         | 60                 | 120                | 85          | 1.01                                      |\n| VIIf      |        | f         | 65                 | 30                 | 87          | 1.47                                      |\n| VIIIh     |        | h         | 60                 | 25                 | 77          | 1.35                                      |\n| VIII      |        | i         | 60                 | 180                | 78          | 0.52                                      |\n\nReaction condition: 2.5 mmol of each monomer; 0.5 mL of pyridine; monomer concentration = ca. 10 wt % in NMP.\n\n$ ^{b} $  Inherent viscosity in NMP of 0.5 g/L at 30°C.\n\nTable II Conditions for the Triphenyl Phosphate Method and Inherent Viscosities of PAIs $ ^{a} $\n\n| Polymer   | DIDA   | Diamine   | Molar Ratio (DIDA : diamine)   | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n|:----------|:-------|:----------|:-------------------------------|:------------|:------------------------------------------|\n| VIIIa     | IV     | a         | 1 : 1                          | 98          | 0.57                                      |\n| VIIIc     |        | c         | 1 : 1                          | 96          | 1.16                                      |\n| VIIId     |        | d         | 1 : 1                          | 91          | 0.54                                      |\n| VIIIe     |        | e         | 1 : 1                          | 94          | 0.80                                      |\n| VIIIf     |        | f         | 1 : 1                          | 95          | 0.92                                      |\n| VIIIg     |        | g         | 1 : 1                          | 95          | 0.88                                      |\n| VIIIh     |        | h         | 1 : 1                          | 97          | 0.84                                      |\n| VIIIi     |        | i         | 1 : 1                          | 94          | 0.39                                      |\n| VIIIj     |        | j         | 1 : 1                          | 95          | 0.76                                      |\n| VIc       | II     | c         | 1.00 : 1.02                    | 97          | 0.71                                      |\n| VId       |        | d         | 1.00 : 1.02                    | 97          | 0.57                                      |\n| VIf       |        | f         | 1.00 : 1.02                    | 98          | 0.72                                      |\n| VIg       |        | g         | 1.00 : 1.02                    | 96          | 0.69                                      |\n| VIi       |        | i         | 1.00 : 1.02                    | 98          | 0.37                                      |\n| VIj       |        | j         | 1.00 : 1.02                    | 96          | 0.76                                      |\n| VIIa      | III    | a         | 1.00 : 1.02                    | 95          | 0.58                                      |\n| VIIc      |        | c         | 1.00 : 1.02                    | 93          | 0.60                                      |\n| VIIf      |        | f         | 1.00 : 1.02                    | 95          | 0.51                                      |\n| VIIh      |        | h         | 1.00 : 1.02                    | 97          | 0.65                                      |\n\n$ ^{a} $  Reaction condition: 2.5 mmol of DIDA and 2.5 (or 2.55) mmol of diamine, 1.5 mL of triphenyl phosphite, 1.2 g of calcium chloride, 4 mL of pyridine in 20 mL of NMP, at 150°C for 3 h.\n\n$ ^{b} $ Inherent viscosity in NMP of 0.5 g/L, at 30°C.\n\nable III Conditions for the One-pot Method and Inherent Viscosities of PAIs $ ^{a} $\n\n| Polymer   | BPDA   | ABA   | Diamine   | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n|:----------|:-------|:------|:----------|:------------|:------------------------------------------|\n| VIa       | s-     | m-    | a         | 91          | 0.51                                      |\n| VIh       | s-     | m-    | h         | 98          | 0.68                                      |\n| VIIc      | a-     | p-    | c         | 90          | 0.56                                      |\n| VIIIh     | a-     | m-    | h         | 88          | 0.50                                      |\n\n$ ^{a} $ Reaction condition: a mixture of 2.5 mmol of s- or a-BPD $ _{4} $  and 5.0 mmol of p- or m-ABA and 7 mL of NMP was refluxed for 4 h, then 2.55 mmol of diamine (molar ratio of DIDA : diamine = 1.00 : 1.02), 1.5 mL of triphenyl phosphite, 1.2 g of calcium chloride, and 4 mL of pyridine were added to the reaction mixture. The polymerization was carried out at 150°C for 3 h.\n\n$ ^{b} $  Inherent viscosity in NMP of 0.5 g/L at 30°C.\n\nBPDA with para- or meta-aminobenzoic acid (p- or m-ABA). For instance, s-BPDA was reacted with two mole equivalents of m-ABA to form an amic acid in homogeneous solution. In a subsequent cyclodehydration reaction, II was formed, which precipitated from the reaction mixture\n\nTable IV Properties of PAIs\n\n| PAI   | Solubility $ ^{a} $   | Solubility $ ^{a} $   | Solubility $ ^{a} $   | Solubility $ ^{a} $   | Solubility $ ^{a} $     | Solubility $ ^{a} $     |\n|:------|:----------------------|:----------------------|:----------------------|:----------------------|:------------------------|:------------------------|\n| PAI   | NMP                   | DMSO                  | py                    | Film $ ^{b} $         | $ T_{g} $ $ ^{c} $ (°C) | $ T_{d} $ $ ^{d} $ (°C) |\n| Va    | ○                     | △                     | ×                     | tough                 | 258                     | 485                     |\n| Vb    | ○                     | △                     | ×                     

In [ ]:
import pandas as pd
import os
import time
polymer_properties_list = []
for i in range(1, 581):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
    user_heading = text
    user_ending = """ Q: Can you summarize the following details of polyamide(PA) in a table: 
            Polyamide name, Glass transition temperature? 
            If any information is not provided or you are unsure, use "Nan". 
            Guidelines:
            1. For the Glass transition temperature (Tg), the format is xxxK or xxx°C.
            2. There may be many different polyamides in an article, so please don't leave them out and use multiple rows to express.
            3. Sometimes the polymers' names seems like nan-polyamides, but they are actually polyamides(e.g. some polyesters, polyarylates ... also contain amide bonds, and are therefore considered polyamides.), please be careful to identify them.
            4. Please only focus on the polyamide homopolymer information, don't include polyamide copolymers.
            5.  **Only output** the Markdown table. Do not include any other text, explanations, or comments. The table must start with the header: `| Polyamide name | Glass transition temperature |`.

            The table should have 2 columns:
            |Polyamide name |Glass transition temperature|

            To help you understand the question, here are some examples:
            Example 1:
            Input:""Polyamides **P4,** **P6,** **P8,** **P10,and** **P12** were syn-thesized by interfacial polycondensation $\mathrm {n}^{6}$ of
                    **Table II Thermal Properties of Polyamides**
                    | Polymer | $T_{g}{}^{\mathrm {a}}\left({}^{\circ }\mathrm {C}\right)$ | $T_{d}{}^{\mathrm {c}}\left({}^{\circ }\mathrm {C}\right)$ |
                    | --- | --- | --- |
                    | P4 | b | 451 |
                    | P6 | 201 | 458 |
                    | P8 | 185 | 459 |
                    | P10 | 166 | 459 |
                    | P12 | 154 | 461 |
                    "Glass transition temperature, observed by DSC in a ni-trogen atmosphere.
                    bNot observed.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | P4 | Nan |
            | P6 | 201°C |
            | P8 | 185°C |
            | P10 | 166°C |
            | P12 | 154°C |

            Example 2:
            Input:"" <!-- PAI GAS TRANSPORT PROPERTIES 2185 -->
                    Table II.Structural and Physical Parameters of $\text {PAIs}^{\mathrm {a}}$ 
                    | Sample | $\begin{array}{c}T_{g}\\ (\mathrm {\sim K})\end{array}$ | r<br>$\left(\mathrm {kg}/\mathrm {m}^{3}\right)$ | $<p>$(nm) | $\left\langle d_{0}\right\rangle$(nm) | FFV | $E_{\mathrm {coh}}$(kJ/mol) |
                    | --- | --- | --- | --- | --- | --- | --- |
                    | PAI(TMI/DPA) | 540 | 1.3012 | 1.18 | 0.55 | 0.1278 | 198.63 |
                    | PAI(TMI/HEA) | 510 | 1.3205 | 1.04 | 0.53 | 0.1298 | 232.33 |
                    | PAI(TMI/TFA) | 527 | 1.4301 | 1.06 | 0.52 | 0.1459 | 273.09 |
                    | PAI(TMI/CDA) | 618 | 1.2581 | 1.60 | 0.60 | 0.1499 | 259.04 |
                    | PAI(PMI/CDA) | 623 | 1.2864 | 1.15 | 0.62 | 0.1551 | 281.23 |
                    a glass transition temperature; $ρ,$  density ( $\left.T=23^{\circ }\mathrm {C}\right);$  ^p&, persistence length; $\left\langle d_{0}\right\rangle ,$  inter-chain distance; FFV, fractional free $T_{g},$ volume $\left(T=23^{\circ }\mathrm {C}\right);E_{\mathrm {coh}}$  molar cohesive energy density.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | PAI(TMI/DPA) | 540K |
            | PAI(TMI/HEA) | 510K |
            | PAI(TMI/TFA) | 527K |
            | PAI(TMI/CDA) | 618K |
            | PAI(PMI/CDA) | 623K |

            Example 3:
            input:"" The diphenolic monomers were prepared using minor modifications of previously published procedures.11 Briefly, each tyrosine alkyl ester was coupled with recrystallized
            3-(4-hydroxyphenyl)-propionic acid (or in some cases, 4-hydroxyphenylacetic acid) using EDCI (1.0 eq.) and HOBt(0.1 eq.) in a solution of either N-methylpyrrolidinone:ethyl
            acetate (1:3; 1.5M concentration of tyrosine ester) or aceto-nitrile (0.75M concentration of tyrosine ester). After aqueousworkup, rotoevaporation, and trituration in hexane, the di-
            phenolic monomers (Figs. 1 and 2) were obtained in puritiesof 96–99% [as measured by high power liquid chromatog- raphy (HPLC) peak ratios or by melting point depressionusing DSC]. Most of the diacids were commercially available in high purity and were recrystallized prior to useFibroblast proliferation was observed to be more sensitive to the chemical structure of the polymer than
            TABLE I
            Room Temperature ( $\left(22^{\circ }\mathrm {C}\right)$  Mechanical Properties of Selected Polyarylates
            | Polymer | $\mathrm {T}_{g}\left({}^{\circ }\mathrm {C}\right)$ | Young’s Modulus (GPa) | Yield Stress (MPa) | Strain at Break (%) |
            | --- | --- | --- | --- | --- |
            | Poly(DTE succinate) | 78 | $1.68\pm 0.17$ | $40.7\pm 3.2$ | $304\pm 102$ |
            | Poly(DTB succinate) | 67 | $1.56\pm 0.18$ | $44.8\pm 3.8$ | $566\pm 36$ |
            | Poly(DTE adipate) | 61 | $1.56\pm 0.10$ | $42.0\pm 4.4$ | $638\pm 152$ |
            | Poly(DTH succinate) | 53 | $1.61\pm 0.10$ | $44.8\pm 2.3$ | $456\pm 103$ |
            | Poly(DTE suberate) | 50 | $1.39\pm 0.10$ | $39.9\pm 3.7$ | $534\pm 91$ |
            | Poly(DTO succinate) | 48 | $1.41\pm 0.18$ | $41.9\pm 4.5$ | $622\pm 68$ |
            | Poly(DTB adipate) | 46 | $1.49\pm 0.22$ | $40.5\pm 3.5$ | $710\pm 96$ |
            | Poly(DTE sebacate) | 44 | $1.44\pm 0.06$ | $34.4\pm 3.1$ | $657\pm 56$ |
            | Poly(DTB suberate) | 37 | $1.24\pm 0.04$ | $31.0\pm 0.8$ | $138\pm 150$ |
            | Poly(DTB sebacate) | 30 | $0.28\pm 0.03$ | $5.8\pm 0.7$ | $744\pm 50$ |
            | Poly(DTO adipate) | 28 | $0.39\pm 0.09$ | $7.6\pm 1.8$ | $676\pm 86$ |
            <!-- STRUCTURE-PROPERTY CORRELATIONS IN COMBINATORIAL LIBRARY 73 -->""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | Poly(DTE succinate) | 78°C |
            | Poly(DTB succinate) | 67°C |
            | Poly(DTE adipate) | 61°C |
            | Poly(DTH succinate) | 53°C |
            | Poly(DTE suberate) | 50°C |
            | Poly(DTO succinate) | 48°C |
            | Poly(DTB adipate) | 46°C |
            | Poly(DTE sebacate) | 44°C |
            | Poly(DTB suberate) | 37°C |
            | Poly(DTB sebacate) | 30°C |
            | Poly(DTO adipate) | 28°C |

            I hope these examples can help you understand the question better. Thank you very much, I hope you can do a good job! 
            A:"""
     
    #client = OpenAI(api_key=api_key, base_url="https://dashscope.aliyuncs.com/compatible-mode/v1")
    client = OpenAI(api_key=api_key, base_url="https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1")
    max_retries = 3 
    retry_wait = 60  
    
    for attempt in range(max_retries):
        try:
            print('get response......')
            response = client.chat.completions.create(
                            model='qwen3.6-plus',
                            messages=[{
                                "role": "system",
                                "content": """Answer the question as truthfully as possible using the provided context,
                                            and if the answer is not contained within the text below, say "Nan" """
                            },
                                {"role": "user", "content": user_heading + user_ending}],
                            extra_body={"enable_thinking":False}
                        )
            answer_str = response.choices[0].message.content
            polymer_properties_list.append(answer_str)
            print(f"Paper {str(i).zfill(3)} processed successfully.")
            break
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < max_retries - 1:  # Retry if not the last attempt
                print(f"Retrying in {retry_wait} seconds...")
                time.sleep(retry_wait)
            else:
                print("All attempts failed. Returning 'Nan'.")
                polymer_properties_list.append("Nan")

Start to analyze paper301
get response......
Paper 301 processed successfully.
Start to analyze paper302
get response......
Paper 302 processed successfully.
Start to analyze paper303
get response......
Paper 303 processed successfully.
Start to analyze paper304
get response......
Paper 304 processed successfully.
Start to analyze paper305
get response......
Paper 305 processed successfully.
Start to analyze paper306
get response......
Paper 306 processed successfully.
Start to analyze paper307
get response......
Paper 307 processed successfully.
Start to analyze paper308
get response......
Paper 308 processed successfully.
Start to analyze paper309
get response......
Paper 309 processed successfully.
Start to analyze paper310
get response......
Paper 310 processed successfully.
Start to analyze paper311
get response......
Paper 311 processed successfully.
Start to analyze paper312
get response......
Paper 312 processed successfully.
Start to analyze paper313
get response......
Paper 313 processed successfully.
Start to analyze paper314
get response......
Paper 314 processed successfully.
Start to analyze paper315
get response......
Paper 315 processed successfully.
Start to analyze paper316
get response......
Paper 316 processed successfully.
Start to analyze paper317
get response......
Paper 317 processed successfully.
Start to analyze paper318
get response......
Paper 318 processed successfully.
Start to analyze paper319
get response......
Paper 319 processed successfully.
Start to analyze paper320
get response......
Paper 320 processed successfully.
Start to analyze paper321
get response......
Paper 321 processed successfully.
Start to analyze paper322
get response......
Paper 322 processed successfully.
Start to analyze paper323
get response......
Paper 323 processed successfully.
Start to analyze paper324
get response......
Paper 324 processed successfully.
Start to analyze paper325
get response......
Paper 325 processed successfully.
Start to analyze paper326
get response......
Paper 326 processed successfully.
Start to analyze paper327
get response......
Paper 327 processed successfully.
Start to analyze paper328
get response......
Paper 328 processed successfully.
Start to analyze paper329
get response......
Paper 329 processed successfully.
Start to analyze paper330
get response......
Paper 330 processed successfully.
Start to analyze paper331
get response......
Paper 331 processed successfully.
Start to analyze paper332
get response......
Paper 332 processed successfully.
Start to analyze paper333
get response......
Paper 333 processed successfully.
Start to analyze paper334
get response......
Paper 334 processed successfully.
Start to analyze paper335
get response......
Paper 335 processed successfully.
Start to analyze paper336
get response......
Paper 336 processed successfully.
Start to analyze paper337
get response......
Paper 337 processed successfully.
Start to analyze paper338
get response......
Paper 338 processed successfully.
Start to analyze paper339
get response......
Paper 339 processed successfully.
Start to analyze paper340
get response......
Paper 340 processed successfully.
Start to analyze paper341
get response......
Paper 341 processed successfully.
Start to analyze paper342
get response......
Paper 342 processed successfully.
Start to analyze paper343
get response......
Paper 343 processed successfully.
Start to analyze paper344
get response......
Paper 344 processed successfully.
Start to analyze paper345
get response......
Paper 345 processed successfully.
Start to analyze paper346
get response......
Paper 346 processed successfully.
Start to analyze paper347
get response......
Paper 347 processed successfully.
Start to analyze paper348
get response......
Paper 348 processed successfully.
Start to analyze paper349
get response......
Paper 349 processed successfully.
Start to analyze paper350
get response......
Paper 350 processed successfully.
Start to analyze paper351
get response......
Paper 351 processed successfully.
Start to analyze paper352
get response......
Paper 352 processed successfully.
Start to analyze paper353
get response......
Paper 353 processed successfully.
Start to analyze paper354
get response......
Paper 354 processed successfully.
Start to analyze paper355
get response......
Paper 355 processed successfully.
Start to analyze paper356
get response......
Paper 356 processed successfully.
Start to analyze paper357
get response......
Paper 357 processed successfully.
Start to analyze paper358
get response......
Paper 358 processed successfully.
Start to analyze paper359
get response......
Paper 359 processed successfully.
Start to analyze paper360
get response......
Paper 360 processed successfully.
Start to analyze paper361
get response......
Paper 361 processed successfully.
Start to analyze paper362
get response......
Paper 362 processed successfully.
Start to analyze paper363
get response......
Paper 363 processed successfully.
Start to analyze paper364
get response......
Paper 364 processed successfully.
Start to analyze paper365
get response......
Paper 365 processed successfully.
Start to analyze paper366
get response......
Paper 366 processed successfully.
Start to analyze paper367
get response......
Paper 367 processed successfully.
Start to analyze paper368
get response......
Paper 368 processed successfully.
Start to analyze paper369
get response......
Paper 369 processed successfully.
Start to analyze paper370
get response......
Paper 370 processed successfully.
Start to analyze paper371
get response......
Paper 371 processed successfully.
Start to analyze paper372
get response......
Paper 372 processed successfully.
Start to analyze paper373
get response......
Paper 373 processed successfully.
Start to analyze paper374
get response......
Paper 374 processed successfully.
Start to analyze paper375
get response......
Paper 375 processed successfully.
Start to analyze paper376
get response......
Paper 376 processed successfully.
Start to analyze paper377
get response......
Paper 377 processed successfully.
Start to analyze paper378
get response......
Paper 378 processed successfully.
Start to analyze paper379
get response......
Paper 379 processed successfully.
Start to analyze paper380
get response......
Paper 380 processed successfully.
Start to analyze paper381
get response......
Paper 381 processed successfully.
Start to analyze paper382
get response......
Paper 382 processed successfully.
Start to analyze paper383
get response......
Paper 383 processed successfully.
Start to analyze paper384
get response......
Paper 384 processed successfully.
Start to analyze paper385
get response......
Paper 385 processed successfully.
Start to analyze paper386
get response......
Paper 386 processed successfully.
Start to analyze paper387
get response......
Paper 387 processed successfully.
Start to analyze paper388
get response......
Paper 388 processed successfully.
Start to analyze paper389
get response......
Paper 389 processed successfully.
Start to analyze paper390
get response......
Paper 390 processed successfully.
Start to analyze paper391
get response......
Paper 391 processed successfully.
Start to analyze paper392
get response......
Paper 392 processed successfully.
Start to analyze paper393
get response......
Paper 393 processed successfully.
Start to analyze paper394
get response......
Paper 394 processed successfully.
Start to analyze paper395
get response......
Paper 395 processed successfully.
Start to analyze paper396
get response......
Paper 396 processed successfully.
Start to analyze paper397
get response......
Paper 397 processed successfully.
Start to analyze paper398
get response......
Paper 398 processed successfully.
Start to analyze paper399
get response......
Paper 399 processed successfully.
Start to analyze paper400
get response......
Paper 400 processed successfully.
Start to analyze paper401
get response......
Paper 401 processed successfully.
Start to analyze paper402
get response......
Paper 402 processed successfully.
Start to analyze paper403
get response......
Paper 403 processed successfully.
Start to analyze paper404
get response......
Paper 404 processed successfully.
Start to analyze paper405
get response......
Paper 405 processed successfully.
Start to analyze paper406
get response......
Paper 406 processed successfully.
Start to analyze paper407
get response......
Paper 407 processed successfully.
Start to analyze paper408
get response......
Paper 408 processed successfully.
Start to analyze paper409
get response......
Paper 409 processed successfully.
Start to analyze paper410
get response......
Paper 410 processed successfully.
Start to analyze paper411
get response......
Paper 411 processed successfully.
Start to analyze paper412
get response......
Paper 412 processed successfully.
Start to analyze paper413
get response......
Paper 413 processed successfully.
Start to analyze paper414
get response......
Paper 414 processed successfully.
Start to analyze paper415
get response......
Paper 415 processed successfully.
Start to analyze paper416
get response......
Paper 416 processed successfully.
Start to analyze paper417
get response......
Paper 417 processed successfully.
Start to analyze paper418
get response......
Paper 418 processed successfully.
Start to analyze paper419
get response......
Paper 419 processed successfully.
Start to analyze paper420
get response......
Paper 420 processed successfully.
Start to analyze paper421
get response......
Paper 421 processed successfully.
Start to analyze paper422
get response......
Paper 422 processed successfully.
Start to analyze paper423
get response......
Paper 423 processed successfully.
Start to analyze paper424
get response......
Paper 424 processed successfully.
Start to analyze paper425
get response......
Paper 425 processed successfully.
Start to analyze paper426
get response......
Paper 426 processed successfully.
Start to analyze paper427
get response......
Paper 427 processed successfully.
Start to analyze paper428
get response......
Paper 428 processed successfully.
Start to analyze paper429
get response......
Paper 429 processed successfully.
Start to analyze paper430
get response......
Paper 430 processed successfully.
Start to analyze paper431
get response......
Paper 431 processed successfully.
Start to analyze paper432
get response......
Paper 432 processed successfully.
Start to analyze paper433
get response......
Paper 433 processed successfully.
Start to analyze paper434
get response......
Paper 434 processed successfully.
Start to analyze paper435
get response......
Paper 435 processed successfully.
Start to analyze paper436
get response......
Paper 436 processed successfully.
Start to analyze paper437
get response......
Paper 437 processed successfully.
Start to analyze paper438
get response......
Paper 438 processed successfully.
Start to analyze paper439
get response......
Paper 439 processed successfully.
Start to analyze paper440
get response......
Paper 440 processed successfully.
Start to analyze paper441
get response......
Paper 441 processed successfully.
Start to analyze paper442
get response......
Paper 442 processed successfully.
Start to analyze paper443
get response......
Paper 443 processed successfully.
Start to analyze paper444
get response......
Paper 444 processed successfully.
Start to analyze paper445
get response......
Paper 445 processed successfully.
Start to analyze paper446
get response......
Paper 446 processed successfully.
Start to analyze paper447
get response......
Paper 447 processed successfully.
Start to analyze paper448
get response......
Paper 448 processed successfully.
Start to analyze paper449
get response......
Paper 449 processed successfully.
Start to analyze paper450
get response......
Paper 450 processed successfully.
Start to analyze paper451
get response......
Paper 451 processed successfully.
Start to analyze paper452
get response......
Paper 452 processed successfully.
Start to analyze paper453
get response......
Paper 453 processed successfully.
Start to analyze paper454
get response......
Paper 454 processed successfully.
Start to analyze paper455
get response......
Paper 455 processed successfully.
Start to analyze paper456
get response......
Paper 456 processed successfully.
Start to analyze paper457
get response......
Paper 457 processed successfully.
Start to analyze paper458
get response......
Paper 458 processed successfully.
Start to analyze paper459
get response......
Paper 459 processed successfully.
Start to analyze paper460
get response......
Paper 460 processed successfully.
Start to analyze paper461
get response......
Paper 461 processed successfully.
Start to analyze paper462
get response......
Paper 462 processed successfully.
Start to analyze paper463
get response......
Paper 463 processed successfully.
Start to analyze paper464
get response......
Paper 464 processed successfully.
Start to analyze paper465
get response......
Paper 465 processed successfully.
Start to analyze paper466
get response......
Paper 466 processed successfully.
Start to analyze paper467
get response......
Paper 467 processed successfully.
Start to analyze paper468
get response......
Paper 468 processed successfully.
Start to analyze paper469
get response......
Paper 469 processed successfully.
Start to analyze paper470
get response......
Paper 470 processed successfully.
Start to analyze paper471
get response......
Paper 471 processed successfully.
Start to analyze paper472
get response......
Paper 472 processed successfully.
Start to analyze paper473
get response......
Paper 473 processed successfully.
Start to analyze paper474
get response......
Paper 474 processed successfully.
Start to analyze paper475
get response......
Paper 475 processed successfully.
Start to analyze paper476
get response......
Paper 476 processed successfully.
Start to analyze paper477
get response......
Paper 477 processed successfully.
Start to analyze paper478
get response......
Paper 478 processed successfully.
Start to analyze paper479
get response......
Paper 479 processed successfully.
Start to analyze paper480
get response......
Paper 480 processed successfully.
Start to analyze paper481
get response......
Paper 481 processed successfully.
Start to analyze paper482
get response......
Paper 482 processed successfully.
Start to analyze paper483
get response......
Paper 483 processed successfully.
Start to analyze paper484
get response......
Paper 484 processed successfully.
Start to analyze paper485
get response......
Paper 485 processed successfully.
Start to analyze paper486
get response......
Paper 486 processed successfully.
Start to analyze paper487
get response......
Paper 487 processed successfully.
Start to analyze paper488
get response......
Paper 488 processed successfully.
Start to analyze paper489
get response......
Paper 489 processed successfully.
Start to analyze paper490
get response......
Paper 490 processed successfully.
Start to analyze paper491
get response......
Paper 491 processed successfully.
Start to analyze paper492
get response......
Paper 492 processed successfully.
Start to analyze paper493
get response......
Paper 493 processed successfully.
Start to analyze paper494
get response......
Paper 494 processed successfully.
Start to analyze paper495
get response......
Paper 495 processed successfully.
Start to analyze paper496
get response......
Paper 496 processed successfully.
Start to analyze paper497
get response......
Paper 497 processed successfully.
Start to analyze paper498
get response......
Paper 498 processed successfully.
Start to analyze paper499
get response......
Paper 499 processed successfully.
Start to analyze paper500
get response......
Paper 500 processed successfully.
Start to analyze paper501
get response......
Paper 501 processed successfully.
Start to analyze paper502
get response......
Paper 502 processed successfully.
Start to analyze paper503
get response......
Paper 503 processed successfully.
Start to analyze paper504
get response......
Paper 504 processed successfully.
Start to analyze paper505
get response......
Paper 505 processed successfully.
Start to analyze paper506
get response......
Paper 506 processed successfully.
Start to analyze paper507
get response......
Paper 507 processed successfully.
Start to analyze paper508
get response......
Paper 508 processed successfully.
Start to analyze paper509
get response......
Paper 509 processed successfully.
Start to analyze paper510
get response......
Paper 510 processed successfully.
Start to analyze paper511
get response......
Paper 511 processed successfully.
Start to analyze paper512
get response......
Paper 512 processed successfully.
Start to analyze paper513
get response......
Paper 513 processed successfully.
Start to analyze paper514
get response......
Paper 514 processed successfully.
Start to analyze paper515
get response......
Paper 515 processed successfully.
Start to analyze paper516
get response......
Paper 516 processed successfully.
Start to analyze paper517
get response......
Paper 517 processed successfully.
Start to analyze paper518
get response......
Paper 518 processed successfully.
Start to analyze paper519
get response......
Paper 519 processed successfully.
Start to analyze paper520
get response......
Paper 520 processed successfully.
Start to analyze paper521
get response......
Paper 521 processed successfully.
Start to analyze paper522
get response......
Paper 522 processed successfully.
Start to analyze paper523
get response......
Paper 523 processed successfully.
Start to analyze paper524
get response......
Paper 524 processed successfully.
Start to analyze paper525
get response......
Paper 525 processed successfully.
Start to analyze paper526
get response......
Paper 526 processed successfully.
Start to analyze paper527
get response......
Paper 527 processed successfully.
Start to analyze paper528
get response......
Paper 528 processed successfully.
Start to analyze paper529
get response......
Paper 529 processed successfully.
Start to analyze paper530
get response......
Paper 530 processed successfully.
Start to analyze paper531
get response......
Paper 531 processed successfully.
Start to analyze paper532
get response......
Paper 532 processed successfully.
Start to analyze paper533
get response......
Paper 533 processed successfully.
Start to analyze paper534
get response......
Paper 534 processed successfully.
Start to analyze paper535
get response......
Paper 535 processed successfully.
Start to analyze paper536
get response......
Paper 536 processed successfully.
Start to analyze paper537
get response......
Paper 537 processed successfully.
Start to analyze paper538
get response......
Paper 538 processed successfully.
Start to analyze paper539
get response......
Paper 539 processed successfully.
Start to analyze paper540
get response......
Paper 540 processed successfully.
Start to analyze paper541
get response......
Paper 541 processed successfully.
Start to analyze paper542
get response......
Paper 542 processed successfully.
Start to analyze paper543
get response......
Paper 543 processed successfully.
Start to analyze paper544
get response......
Paper 544 processed successfully.
Start to analyze paper545
get response......
Paper 545 processed successfully.
Start to analyze paper546
get response......
Paper 546 processed successfully.
Start to analyze paper547
get response......
Paper 547 processed successfully.
Start to analyze paper548
get response......
Paper 548 processed successfully.
Start to analyze paper549
get response......
Paper 549 processed successfully.
Start to analyze paper550
get response......
Paper 550 processed successfully.
Start to analyze paper551
get response......
Paper 551 processed successfully.
Start to analyze paper552
get response......
Paper 552 processed successfully.
Start to analyze paper553
get response......
Paper 553 processed successfully.

In [4]:
print(polymer_properties_list[0])

| Polyamide name | Glass transition temperature |
| :--- | :--- |
| PA30 | 51°C |
| PA90 | 58°C |

In [ ]:
# import pickle
# with open('polymer_properties_list_qwen3.6-plus(301_580).pkl', 'wb') as f:
#     pickle.dump(polymer_properties_list, f)

In [48]:
import pickle
with open('polymer_properties_list_qwen3.6-plus(001_100).pkl', 'rb') as f:
    loaded_list_0_100 = pickle.load(f)

with open('polymer_properties_list_qwen3.6-plus(101_300).pkl', 'rb') as f:
    loaded_list_101_300 = pickle.load(f)

with open('polymer_properties_list_qwen3.6-plus(301_580).pkl', 'rb') as f:
    loaded_list_301_580 = pickle.load(f)

In [49]:
import io
import re
import pandas as pd

def parse_loaded_list_to_df(loaded_list, start_id):
    all_dataframes = []

    for index, answer_str in enumerate(loaded_list, start=start_id):
        # 改进后的正则：允许最后一行无换行
        table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
        if table_match:
            table_str = table_match[0]

            # 去掉每行两边的 |，避免 read_csv 产生空列
            table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

            data_io = io.StringIO(table_str)
            try:
                df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
                df.columns = df.columns.str.strip()
                df = df.dropna(how="all")
                df = df.reset_index(drop=True)
                df["ID"] = index
                all_dataframes.append(df)
            except Exception as e:
                print(f"Error parsing entry {index}: {e}")
        else:
            print(f"No table found in entry {index}")

    combined_df = pd.concat(all_dataframes, ignore_index=True)

    return combined_df

df_qwen_0_100 = parse_loaded_list_to_df(
    loaded_list_0_100,
    start_id=1
)

df_qwen_101_300 = parse_loaded_list_to_df(
    loaded_list_101_300,
    start_id=101
)

df_qwen_301_580 = parse_loaded_list_to_df(
    loaded_list_301_580,
    start_id=301
)

No table found in entry 2
No table found in entry 3
No table found in entry 5
No table found in entry 12
No table found in entry 15
No table found in entry 25
No table found in entry 28
No table found in entry 57
No table found in entry 61
No table found in entry 114
No table found in entry 121
No table found in entry 130
No table found in entry 137
No table found in entry 147
No table found in entry 177
No table found in entry 179
No table found in entry 190
No table found in entry 197
No table found in entry 206
No table found in entry 230
No table found in entry 242
No table found in entry 247
No table found in entry 258
No table found in entry 260
No table found in entry 264
No table found in entry 265
No table found in entry 280
No table found in entry 286
No table found in entry 294
No table found in entry 295
No table found in entry 303
No table found in entry 328
No table found in entry 335
No table found in entry 337
No table found in entry 357
No table found in entry 360
No table found in entry 387
No table found in entry 396
No table found in entry 397
No table found in entry 398
No table found in entry 403
No table found in entry 405
No table found in entry 425
No table found in entry 429
No table found in entry 435
No table found in entry 436
No table found in entry 439
No table found in entry 452
No table found in entry 457
No table found in entry 464
No table found in entry 478
No table found in entry 482
No table found in entry 488
No table found in entry 497
No table found in entry 513
No table found in entry 516
No table found in entry 517
No table found in entry 521
No table found in entry 522
No table found in entry 523
No table found in entry 526
No table found in entry 536
No table found in entry 539
No table found in entry 544
No table found in entry 545
No table found in entry 571

In [50]:
df_PA_qwen_plus = pd.concat(
    [
        df_qwen_0_100,
        df_qwen_101_300,
        df_qwen_301_580
    ],
    ignore_index=True
)

In [52]:
df_PA_qwen_plus = df_PA_qwen_plus[~df_PA_qwen_plus.apply(lambda row: row.astype(str).str.contains('---').any(), axis=1)]
df_cleaned = df_PA_qwen_plus[~df_PA_qwen_plus.apply(lambda row: row.astype(str).str.contains('--').any(), axis=1)]
def remove_temp_unit(x):
    try:
        if 'K' in str(x):
            return float(str(x).replace('K', ''))
        elif '°C' in str(x):
            return float(str(x).replace('°C', ''))
        else:
            return x
    except ValueError:
        return x

df_cleaned['Glass transition temperature'] = df_cleaned['Glass transition temperature'].apply(remove_temp_unit)
df_cleaned=df_cleaned.reset_index(drop=True)
df_cleaned

     Polyamide name Glass transition temperature   ID
0               Va                         258.0    1
1               Vb                         262.0    1
2               Vi                         256.0    1
3              VIa                         258.0    1
4              VIc                         270.0    1
...             ...                          ...  ...
2071         PA 46                          78.0  578
2072         PA 66                          65.0  578
2073          PA 6                          58.0  578
2074          PA 6                         315.3  579
2075       Nylon 6                          Nan   580

[2076 rows x 3 columns]

In [ ]:
#df_cleaned.to_excel('PA_qwen36plus_extraction.xlsx', index=False)

### deepseek-v3.2

In [ ]:
import pandas as pd
import os
import time
polymer_properties_list = []
for i in range(1, 581):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
    user_heading = text
    user_ending = """ Q: Can you summarize the following details of polyamide(PA) in a table: 
            Polyamide name, Glass transition temperature? 
            If any information is not provided or you are unsure, use "Nan". 
            Guidelines:
            1. For the Glass transition temperature (Tg), the format is xxxK or xxx°C.
            2. There may be many different polyamides in an article, so please don't leave them out and use multiple rows to express.
            3. Sometimes the polymers' names seems like nan-polyamides, but they are actually polyamides(e.g. some polyesters, polyarylates ... also contain amide bonds, and are therefore considered polyamides.), please be careful to identify them.
            4. Please only focus on the polyamide homopolymer information, don't include polyamide copolymers.
            5.  **Only output** the Markdown table. Do not include any other text, explanations, or comments. The table must start with the header: `| Polyamide name | Glass transition temperature |`.

            The table should have 2 columns:
            |Polyamide name |Glass transition temperature|

            To help you understand the question, here are some examples:
            Example 1:
            Input:""Polyamides **P4,** **P6,** **P8,** **P10,and** **P12** were syn-thesized by interfacial polycondensation $\mathrm {n}^{6}$ of
                    **Table II Thermal Properties of Polyamides**
                    | Polymer | $T_{g}{}^{\mathrm {a}}\left({}^{\circ }\mathrm {C}\right)$ | $T_{d}{}^{\mathrm {c}}\left({}^{\circ }\mathrm {C}\right)$ |
                    | --- | --- | --- |
                    | P4 | b | 451 |
                    | P6 | 201 | 458 |
                    | P8 | 185 | 459 |
                    | P10 | 166 | 459 |
                    | P12 | 154 | 461 |
                    "Glass transition temperature, observed by DSC in a ni-trogen atmosphere.
                    bNot observed.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | P4 | Nan |
            | P6 | 201°C |
            | P8 | 185°C |
            | P10 | 166°C |
            | P12 | 154°C |

            Example 2:
            Input:"" <!-- PAI GAS TRANSPORT PROPERTIES 2185 -->
                    Table II.Structural and Physical Parameters of $\text {PAIs}^{\mathrm {a}}$ 
                    | Sample | $\begin{array}{c}T_{g}\\ (\mathrm {\sim K})\end{array}$ | r<br>$\left(\mathrm {kg}/\mathrm {m}^{3}\right)$ | $<p>$(nm) | $\left\langle d_{0}\right\rangle$(nm) | FFV | $E_{\mathrm {coh}}$(kJ/mol) |
                    | --- | --- | --- | --- | --- | --- | --- |
                    | PAI(TMI/DPA) | 540 | 1.3012 | 1.18 | 0.55 | 0.1278 | 198.63 |
                    | PAI(TMI/HEA) | 510 | 1.3205 | 1.04 | 0.53 | 0.1298 | 232.33 |
                    | PAI(TMI/TFA) | 527 | 1.4301 | 1.06 | 0.52 | 0.1459 | 273.09 |
                    | PAI(TMI/CDA) | 618 | 1.2581 | 1.60 | 0.60 | 0.1499 | 259.04 |
                    | PAI(PMI/CDA) | 623 | 1.2864 | 1.15 | 0.62 | 0.1551 | 281.23 |
                    a glass transition temperature; $ρ,$  density ( $\left.T=23^{\circ }\mathrm {C}\right);$  ^p&, persistence length; $\left\langle d_{0}\right\rangle ,$  inter-chain distance; FFV, fractional free $T_{g},$ volume $\left(T=23^{\circ }\mathrm {C}\right);E_{\mathrm {coh}}$  molar cohesive energy density.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | PAI(TMI/DPA) | 540K |
            | PAI(TMI/HEA) | 510K |
            | PAI(TMI/TFA) | 527K |
            | PAI(TMI/CDA) | 618K |
            | PAI(PMI/CDA) | 623K |

            Example 3:
            input:"" The diphenolic monomers were prepared using minor modifications of previously published procedures.11 Briefly, each tyrosine alkyl ester was coupled with recrystallized
            3-(4-hydroxyphenyl)-propionic acid (or in some cases, 4-hydroxyphenylacetic acid) using EDCI (1.0 eq.) and HOBt(0.1 eq.) in a solution of either N-methylpyrrolidinone:ethyl
            acetate (1:3; 1.5M concentration of tyrosine ester) or aceto-nitrile (0.75M concentration of tyrosine ester). After aqueousworkup, rotoevaporation, and trituration in hexane, the di-
            phenolic monomers (Figs. 1 and 2) were obtained in puritiesof 96–99% [as measured by high power liquid chromatog- raphy (HPLC) peak ratios or by melting point depressionusing DSC]. Most of the diacids were commercially available in high purity and were recrystallized prior to useFibroblast proliferation was observed to be more sensitive to the chemical structure of the polymer than
            TABLE I
            Room Temperature ( $\left(22^{\circ }\mathrm {C}\right)$  Mechanical Properties of Selected Polyarylates
            | Polymer | $\mathrm {T}_{g}\left({}^{\circ }\mathrm {C}\right)$ | Young’s Modulus (GPa) | Yield Stress (MPa) | Strain at Break (%) |
            | --- | --- | --- | --- | --- |
            | Poly(DTE succinate) | 78 | $1.68\pm 0.17$ | $40.7\pm 3.2$ | $304\pm 102$ |
            | Poly(DTB succinate) | 67 | $1.56\pm 0.18$ | $44.8\pm 3.8$ | $566\pm 36$ |
            | Poly(DTE adipate) | 61 | $1.56\pm 0.10$ | $42.0\pm 4.4$ | $638\pm 152$ |
            | Poly(DTH succinate) | 53 | $1.61\pm 0.10$ | $44.8\pm 2.3$ | $456\pm 103$ |
            | Poly(DTE suberate) | 50 | $1.39\pm 0.10$ | $39.9\pm 3.7$ | $534\pm 91$ |
            | Poly(DTO succinate) | 48 | $1.41\pm 0.18$ | $41.9\pm 4.5$ | $622\pm 68$ |
            | Poly(DTB adipate) | 46 | $1.49\pm 0.22$ | $40.5\pm 3.5$ | $710\pm 96$ |
            | Poly(DTE sebacate) | 44 | $1.44\pm 0.06$ | $34.4\pm 3.1$ | $657\pm 56$ |
            | Poly(DTB suberate) | 37 | $1.24\pm 0.04$ | $31.0\pm 0.8$ | $138\pm 150$ |
            | Poly(DTB sebacate) | 30 | $0.28\pm 0.03$ | $5.8\pm 0.7$ | $744\pm 50$ |
            | Poly(DTO adipate) | 28 | $0.39\pm 0.09$ | $7.6\pm 1.8$ | $676\pm 86$ |
            <!-- STRUCTURE-PROPERTY CORRELATIONS IN COMBINATORIAL LIBRARY 73 -->""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | Poly(DTE succinate) | 78°C |
            | Poly(DTB succinate) | 67°C |
            | Poly(DTE adipate) | 61°C |
            | Poly(DTH succinate) | 53°C |
            | Poly(DTE suberate) | 50°C |
            | Poly(DTO succinate) | 48°C |
            | Poly(DTB adipate) | 46°C |
            | Poly(DTE sebacate) | 44°C |
            | Poly(DTB suberate) | 37°C |
            | Poly(DTB sebacate) | 30°C |
            | Poly(DTO adipate) | 28°C |

            I hope these examples can help you understand the question better. Thank you very much, I hope you can do a good job! 
            A:"""
     
    #client = OpenAI(api_key=api_key, base_url="https://dashscope.aliyuncs.com/compatible-mode/v1")
    client = OpenAI(api_key=api_key, base_url="https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1")
    max_retries = 3 
    retry_wait = 60  
    
    for attempt in range(max_retries):
        try:
            print('get response......')
            response = client.chat.completions.create(
                            model='deepseek-v3.2',
                            messages=[{
                                "role": "system",
                                "content": """Answer the question as truthfully as possible using the provided context,
                                            and if the answer is not contained within the text below, say "Nan" """
                            },
                                {"role": "user", "content": user_heading + user_ending}],
                            extra_body={"enable_thinking":False}
                        )
            answer_str = response.choices[0].message.content
            polymer_properties_list.append(answer_str)
            print(f"Paper {str(i).zfill(3)} processed successfully.")
            break
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < max_retries - 1:  # Retry if not the last attempt
                print(f"Retrying in {retry_wait} seconds...")
                time.sleep(retry_wait)
            else:
                print("All attempts failed. Returning 'Nan'.")
                polymer_properties_list.append("Nan")

Start to analyze paper301
get response......
Paper 301 processed successfully.
Start to analyze paper302
get response......
Paper 302 processed successfully.
Start to analyze paper303
get response......
Paper 303 processed successfully.
Start to analyze paper304
get response......
Paper 304 processed successfully.
Start to analyze paper305
get response......
Paper 305 processed successfully.
Start to analyze paper306
get response......
Paper 306 processed successfully.
Start to analyze paper307
get response......
Paper 307 processed successfully.
Start to analyze paper308
get response......
Paper 308 processed successfully.
Start to analyze paper309
get response......
Paper 309 processed successfully.
Start to analyze paper310
get response......
Paper 310 processed successfully.
Start to analyze paper311
get response......
Paper 311 processed successfully.
Start to analyze paper312
get response......
Paper 312 processed successfully.
Start to analyze paper313
get response......
Paper 313 processed successfully.
Start to analyze paper314
get response......
Paper 314 processed successfully.
Start to analyze paper315
get response......
Paper 315 processed successfully.
Start to analyze paper316
get response......
Paper 316 processed successfully.
Start to analyze paper317
get response......
Paper 317 processed successfully.
Start to analyze paper318
get response......
Paper 318 processed successfully.
Start to analyze paper319
get response......
Paper 319 processed successfully.
Start to analyze paper320
get response......
Paper 320 processed successfully.
Start to analyze paper321
get response......
Paper 321 processed successfully.
Start to analyze paper322
get response......
Paper 322 processed successfully.
Start to analyze paper323
get response......
Paper 323 processed successfully.
Start to analyze paper324
get response......
Paper 324 processed successfully.
Start to analyze paper325
get response......
Paper 325 processed successfully.
Start to analyze paper326
get response......
Paper 326 processed successfully.
Start to analyze paper327
get response......
Paper 327 processed successfully.
Start to analyze paper328
get response......
Paper 328 processed successfully.
Start to analyze paper329
get response......
Paper 329 processed successfully.
Start to analyze paper330
get response......
Paper 330 processed successfully.
Start to analyze paper331
get response......
Paper 331 processed successfully.
Start to analyze paper332
get response......
Paper 332 processed successfully.
Start to analyze paper333
get response......
Paper 333 processed successfully.
Start to analyze paper334
get response......
Paper 334 processed successfully.
Start to analyze paper335
get response......
Paper 335 processed successfully.
Start to analyze paper336
get response......
Paper 336 processed successfully.
Start to analyze paper337
get response......
Paper 337 processed successfully.
Start to analyze paper338
get response......
Paper 338 processed successfully.
Start to analyze paper339
get response......
Paper 339 processed successfully.
Start to analyze paper340
get response......
Paper 340 processed successfully.
Start to analyze paper341
get response......
Paper 341 processed successfully.
Start to analyze paper342
get response......
Paper 342 processed successfully.
Start to analyze paper343
get response......
Paper 343 processed successfully.
Start to analyze paper344
get response......
Paper 344 processed successfully.
Start to analyze paper345
get response......
Paper 345 processed successfully.
Start to analyze paper346
get response......
Paper 346 processed successfully.
Start to analyze paper347
get response......
Paper 347 processed successfully.
Start to analyze paper348
get response......
Paper 348 processed successfully.
Start to analyze paper349
get response......
Paper 349 processed successfully.
Start to analyze paper350
get response......
Paper 350 processed successfully.
Start to analyze paper351
get response......
Paper 351 processed successfully.
Start to analyze paper352
get response......
Paper 352 processed successfully.
Start to analyze paper353
get response......
Paper 353 processed successfully.
Start to analyze paper354
get response......
Paper 354 processed successfully.
Start to analyze paper355
get response......
Paper 355 processed successfully.
Start to analyze paper356
get response......
Paper 356 processed successfully.
Start to analyze paper357
get response......
Paper 357 processed successfully.
Start to analyze paper358
get response......
Paper 358 processed successfully.
Start to analyze paper359
get response......
Paper 359 processed successfully.
Start to analyze paper360
get response......
Paper 360 processed successfully.
Start to analyze paper361
get response......
Paper 361 processed successfully.
Start to analyze paper362
get response......
Paper 362 processed successfully.
Start to analyze paper363
get response......
Paper 363 processed successfully.
Start to analyze paper364
get response......
Paper 364 processed successfully.
Start to analyze paper365
get response......
Paper 365 processed successfully.
Start to analyze paper366
get response......
Paper 366 processed successfully.
Start to analyze paper367
get response......
Paper 367 processed successfully.
Start to analyze paper368
get response......
Paper 368 processed successfully.
Start to analyze paper369
get response......
Paper 369 processed successfully.
Start to analyze paper370
get response......
Paper 370 processed successfully.
Start to analyze paper371
get response......
Paper 371 processed successfully.
Start to analyze paper372
get response......
Paper 372 processed successfully.
Start to analyze paper373
get response......
Paper 373 processed successfully.
Start to analyze paper374
get response......
Paper 374 processed successfully.
Start to analyze paper375
get response......
Paper 375 processed successfully.
Start to analyze paper376
get response......
Paper 376 processed successfully.
Start to analyze paper377
get response......
Paper 377 processed successfully.
Start to analyze paper378
get response......
Paper 378 processed successfully.
Start to analyze paper379
get response......
Paper 379 processed successfully.
Start to analyze paper380
get response......
Paper 380 processed successfully.
Start to analyze paper381
get response......
Paper 381 processed successfully.
Start to analyze paper382
get response......
Paper 382 processed successfully.
Start to analyze paper383
get response......
Paper 383 processed successfully.
Start to analyze paper384
get response......
Paper 384 processed successfully.
Start to analyze paper385
get response......
Paper 385 processed successfully.
Start to analyze paper386
get response......
Paper 386 processed successfully.
Start to analyze paper387
get response......
Paper 387 processed successfully.
Start to analyze paper388
get response......
Paper 388 processed successfully.
Start to analyze paper389
get response......
Paper 389 processed successfully.
Start to analyze paper390
get response......
Paper 390 processed successfully.
Start to analyze paper391
get response......
Paper 391 processed successfully.
Start to analyze paper392
get response......
Paper 392 processed successfully.
Start to analyze paper393
get response......
Paper 393 processed successfully.
Start to analyze paper394
get response......
Paper 394 processed successfully.
Start to analyze paper395
get response......
Paper 395 processed successfully.
Start to analyze paper396
get response......
Paper 396 processed successfully.
Start to analyze paper397
get response......
Paper 397 processed successfully.
Start to analyze paper398
get response......
Paper 398 processed successfully.
Start to analyze paper399
get response......
Paper 399 processed successfully.
Start to analyze paper400
get response......
Paper 400 processed successfully.
Start to analyze paper401
get response......
Paper 401 processed successfully.
Start to analyze paper402
get response......
Paper 402 processed successfully.
Start to analyze paper403
get response......
Paper 403 processed successfully.
Start to analyze paper404
get response......
Paper 404 processed successfully.
Start to analyze paper405
get response......
Paper 405 processed successfully.
Start to analyze paper406
get response......
Paper 406 processed successfully.
Start to analyze paper407
get response......
Paper 407 processed successfully.
Start to analyze paper408
get response......
Paper 408 processed successfully.
Start to analyze paper409
get response......
Paper 409 processed successfully.
Start to analyze paper410
get response......
Paper 410 processed successfully.
Start to analyze paper411
get response......
Paper 411 processed successfully.
Start to analyze paper412
get response......
Paper 412 processed successfully.
Start to analyze paper413
get response......
Paper 413 processed successfully.
Start to analyze paper414
get response......
Paper 414 processed successfully.
Start to analyze paper415
get response......
Paper 415 processed successfully.
Start to analyze paper416
get response......
Paper 416 processed successfully.
Start to analyze paper417
get response......
Paper 417 processed successfully.
Start to analyze paper418
get response......
Paper 418 processed successfully.
Start to analyze paper419
get response......
Paper 419 processed successfully.
Start to analyze paper420
get response......
Paper 420 processed successfully.
Start to analyze paper421
get response......
Paper 421 processed successfully.
Start to analyze paper422
get response......
Paper 422 processed successfully.
Start to analyze paper423
get response......
Paper 423 processed successfully.
Start to analyze paper424
get response......
Paper 424 processed successfully.
Start to analyze paper425
get response......
Paper 425 processed successfully.
Start to analyze paper426
get response......
Paper 426 processed successfully.
Start to analyze paper427
get response......
Paper 427 processed successfully.
Start to analyze paper428
get response......
Paper 428 processed successfully.
Start to analyze paper429
get response......
Paper 429 processed successfully.
Start to analyze paper430
get response......
Paper 430 processed successfully.
Start to analyze paper431
get response......
Paper 431 processed successfully.
Start to analyze paper432
get response......
Paper 432 processed successfully.
Start to analyze paper433
get response......
Paper 433 processed successfully.
Start to analyze paper434
get response......
Paper 434 processed successfully.
Start to analyze paper435
get response......
Paper 435 processed successfully.
Start to analyze paper436
get response......
Paper 436 processed successfully.
Start to analyze paper437
get response......
Paper 437 processed successfully.
Start to analyze paper438
get response......
Paper 438 processed successfully.
Start to analyze paper439
get response......
Paper 439 processed successfully.
Start to analyze paper440
get response......
Paper 440 processed successfully.
Start to analyze paper441
get response......
Paper 441 processed successfully.
Start to analyze paper442
get response......
Paper 442 processed successfully.
Start to analyze paper443
get response......
Paper 443 processed successfully.
Start to analyze paper444
get response......
Paper 444 processed successfully.
Start to analyze paper445
get response......
Paper 445 processed successfully.
Start to analyze paper446
get response......
Paper 446 processed successfully.
Start to analyze paper447
get response......
Paper 447 processed successfully.
Start to analyze paper448
get response......
Paper 448 processed successfully.
Start to analyze paper449
get response......
Paper 449 processed successfully.
Start to analyze paper450
get response......
Paper 450 processed successfully.
Start to analyze paper451
get response......
Paper 451 processed successfully.
Start to analyze paper452
get response......
Paper 452 processed successfully.
Start to analyze paper453
get response......
Paper 453 processed successfully.
Start to analyze paper454
get response......
Paper 454 processed successfully.
Start to analyze paper455
get response......
Paper 455 processed successfully.
Start to analyze paper456
get response......
Paper 456 processed successfully.
Start to analyze paper457
get response......
Paper 457 processed successfully.
Start to analyze paper458
get response......
Paper 458 processed successfully.
Start to analyze paper459
get response......
Paper 459 processed successfully.
Start to analyze paper460
get response......
Paper 460 processed successfully.
Start to analyze paper461
get response......
Paper 461 processed successfully.
Start to analyze paper462
get response......
Paper 462 processed successfully.
Start to analyze paper463
get response......
Paper 463 processed successfully.
Start to analyze paper464
get response......
Paper 464 processed successfully.
Start to analyze paper465
get response......
Paper 465 processed successfully.
Start to analyze paper466
get response......
Paper 466 processed successfully.
Start to analyze paper467
get response......
Paper 467 processed successfully.
Start to analyze paper468
get response......
Paper 468 processed successfully.
Start to analyze paper469
get response......
Paper 469 processed successfully.
Start to analyze paper470
get response......
Paper 470 processed successfully.
Start to analyze paper471
get response......
Paper 471 processed successfully.
Start to analyze paper472
get response......
Paper 472 processed successfully.
Start to analyze paper473
get response......
Paper 473 processed successfully.
Start to analyze paper474
get response......
Paper 474 processed successfully.
Start to analyze paper475
get response......
Paper 475 processed successfully.
Start to analyze paper476
get response......
Paper 476 processed successfully.
Start to analyze paper477
get response......
Paper 477 processed successfully.
Start to analyze paper478
get response......
Paper 478 processed successfully.
Start to analyze paper479
get response......
Paper 479 processed successfully.
Start to analyze paper480
get response......
Paper 480 processed successfully.
Start to analyze paper481
get response......
Paper 481 processed successfully.
Start to analyze paper482
get response......
Paper 482 processed successfully.
Start to analyze paper483
get response......
Paper 483 processed successfully.
Start to analyze paper484
get response......
Paper 484 processed successfully.
Start to analyze paper485
get response......
Paper 485 processed successfully.
Start to analyze paper486
get response......
Paper 486 processed successfully.
Start to analyze paper487
get response......
Paper 487 processed successfully.
Start to analyze paper488
get response......
Paper 488 processed successfully.
Start to analyze paper489
get response......
Paper 489 processed successfully.
Start to analyze paper490
get response......
Paper 490 processed successfully.
Start to analyze paper491
get response......
Paper 491 processed successfully.
Start to analyze paper492
get response......
Paper 492 processed successfully.
Start to analyze paper493
get response......
Paper 493 processed successfully.
Start to analyze paper494
get response......
Paper 494 processed successfully.
Start to analyze paper495
get response......
Paper 495 processed successfully.
Start to analyze paper496
get response......
Paper 496 processed successfully.
Start to analyze paper497
get response......
Paper 497 processed successfully.
Start to analyze paper498
get response......
Paper 498 processed successfully.
Start to analyze paper499
get response......
Paper 499 processed successfully.
Start to analyze paper500
get response......
Paper 500 processed successfully.
Start to analyze paper501
get response......
Paper 501 processed successfully.
Start to analyze paper502
get response......
Paper 502 processed successfully.
Start to analyze paper503
get response......
Paper 503 processed successfully.
Start to analyze paper504
get response......
Paper 504 processed successfully.
Start to analyze paper505
get response......
Paper 505 processed successfully.
Start to analyze paper506
get response......
Paper 506 processed successfully.
Start to analyze paper507
get response......
Paper 507 processed successfully.
Start to analyze paper508
get response......
Paper 508 processed successfully.
Start to analyze paper509
get response......
Paper 509 processed successfully.
Start to analyze paper510
get response......
Paper 510 processed successfully.
Start to analyze paper511
get response......
Paper 511 processed successfully.
Start to analyze paper512
get response......
Paper 512 processed successfully.
Start to analyze paper513
get response......
Paper 513 processed successfully.
Start to analyze paper514
get response......
Paper 514 processed successfully.
Start to analyze paper515
get response......
Paper 515 processed successfully.
Start to analyze paper516
get response......
Paper 516 processed successfully.
Start to analyze paper517
get response......
Paper 517 processed successfully.
Start to analyze paper518
get response......
Paper 518 processed successfully.
Start to analyze paper519
get response......
Paper 519 processed successfully.
Start to analyze paper520
get response......
Paper 520 processed successfully.
Start to analyze paper521
get response......
Paper 521 processed successfully.
Start to analyze paper522
get response......
Paper 522 processed successfully.
Start to analyze paper523
get response......
Paper 523 processed successfully.
Start to analyze paper524
get response......
Paper 524 processed successfully.
Start to analyze paper525
get response......
Paper 525 processed successfully.
Start to analyze paper526
get response......
Paper 526 processed successfully.
Start to analyze paper527
get response......
Paper 527 processed successfully.
Start to analyze paper528
get response......
Paper 528 processed successfully.
Start to analyze paper529
get response......
Paper 529 processed successfully.
Start to analyze paper530
get response......
Paper 530 processed successfully.
Start to analyze paper531
get response......
Paper 531 processed successfully.
Start to analyze paper532
get response......
Paper 532 processed successfully.
Start to analyze paper533
get response......
Paper 533 processed successfully.
Start to analyze paper534
get response......
Paper 534 processed successfully.
Start to analyze paper535
get response......
Paper 535 processed successfully.
Start to analyze paper536
get response......
Paper 536 processed successfully.
Start to analyze paper537
get response......
Paper 537 processed successfully.
Start to analyze paper538
get response......
Paper 538 processed successfully.
Start to analyze paper539
get response......
Paper 539 processed successfully.
Start to analyze paper540
get response......
Paper 540 processed successfully.
Start to analyze paper541
get response......
Paper 541 processed successfully.
Start to analyze paper542
get response......
Paper 542 processed successfully.
Start to analyze paper543
get response......
Paper 543 processed successfully.
Start to analyze paper544
get response......
Paper 544 processed successfully.
Start to analyze paper545
get response......
Paper 545 processed successfully.
Start to analyze paper546
get response......
Paper 546 processed successfully.
Start to analyze paper547
get response......
Paper 547 processed successfully.
Start to analyze paper548
get response......
Paper 548 processed successfully.
Start to analyze paper549
get response......
Paper 549 processed successfully.
Start to analyze paper550
get response......
Paper 550 processed successfully.
Start to analyze paper551
get response......
Paper 551 processed successfully.
Start to analyze paper552
get response......
Paper 552 processed successfully.
Start to analyze paper553
get response......
Paper 553 processed successfully.

In [ ]:
# import pickle
# with open('polymer_properties_list_deepseek-v3.2(301_580).pkl', 'wb') as f:
#     pickle.dump(polymer_properties_list, f)

In [57]:
import pickle
with open('polymer_properties_list_deepseek-v3.2(1_300).pkl', 'rb') as f:
    loaded_list_0_300 = pickle.load(f)

with open('polymer_properties_list_deepseek-v3.2(301_580).pkl', 'rb') as f:
    loaded_list_301_580 = pickle.load(f)

In [58]:
import io
import re
import pandas as pd

def parse_loaded_list_to_df(loaded_list, start_id):
    all_dataframes = []

    for index, answer_str in enumerate(loaded_list, start=start_id):
        # 改进后的正则：允许最后一行无换行
        table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
        if table_match:
            table_str = table_match[0]

            # 去掉每行两边的 |，避免 read_csv 产生空列
            table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

            data_io = io.StringIO(table_str)
            try:
                df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
                df.columns = df.columns.str.strip()
                df = df.dropna(how="all")
                df = df.reset_index(drop=True)
                df["ID"] = index
                all_dataframes.append(df)
            except Exception as e:
                print(f"Error parsing entry {index}: {e}")
        else:
            print(f"No table found in entry {index}")

    combined_df = pd.concat(all_dataframes, ignore_index=True)

    return combined_df

df_dsv32_0_300 = parse_loaded_list_to_df(
    loaded_list_0_300,
    start_id=1
)

df_dsv32_301_580 = parse_loaded_list_to_df(
    loaded_list_301_580,
    start_id=301
)

No table found in entry 147

In [59]:
df_PA_deepseek_v32 = pd.concat(
    [
        df_dsv32_0_300,
        df_dsv32_301_580
    ],
    ignore_index=True
)

In [60]:
df_PA_deepseek_v32 = df_PA_deepseek_v32[~df_PA_deepseek_v32.apply(lambda row: row.astype(str).str.contains('---').any(), axis=1)]
df_cleaned = df_PA_deepseek_v32[~df_PA_deepseek_v32.apply(lambda row: row.astype(str).str.contains('--').any(), axis=1)]
def remove_temp_unit(x):
    try:
        if 'K' in str(x):
            return float(str(x).replace('K', ''))
        elif '°C' in str(x):
            return float(str(x).replace('°C', ''))
        else:
            return x
    except ValueError:
        return x

df_cleaned['Glass transition temperature'] = df_cleaned['Glass transition temperature'].apply(remove_temp_unit)
df_cleaned=df_cleaned.reset_index(drop=True)
df_cleaned

       Polyamide name Glass transition temperature   ID
0     Va                                     258.0    1
1     Vb                                     262.0    1
2     Vi                                     256.0    1
3     VIa                                    258.0    1
4     VIc                                    270.0    1
...               ...                          ...  ...
2130  PA 46                                   78.0  578
2131  PA 66                                   65.0  578
2132  PA 6                                    58.0  578
2133  PA 6                                   315.3  579
2134         nylon 6                          Nan   580

[2135 rows x 3 columns]

In [62]:
df_cleaned.to_excel('PA_dsv32_extraction.xlsx', index=False)

### GLM

In [3]:
import pandas as pd
import os
import time
polymer_properties_list = []
for i in range(1, 581):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
    user_heading = text
    user_ending = """ Q: Can you summarize the following details of polyamide(PA) in a table: 
            Polyamide name, Glass transition temperature? 
            If any information is not provided or you are unsure, use "Nan". 
            Guidelines:
            1. For the Glass transition temperature (Tg), the format is xxxK or xxx°C.
            2. There may be many different polyamides in an article, so please don't leave them out and use multiple rows to express.
            3. Sometimes the polymers' names seems like nan-polyamides, but they are actually polyamides(e.g. some polyesters, polyarylates ... also contain amide bonds, and are therefore considered polyamides.), please be careful to identify them.
            4. Please only focus on the polyamide homopolymer information, don't include polyamide copolymers.
            5.  **Only output** the Markdown table. Do not include any other text, explanations, or comments. The table must start with the header: `| Polyamide name | Glass transition temperature |`.

            The table should have 2 columns:
            |Polyamide name |Glass transition temperature|

            To help you understand the question, here are some examples:
            Example 1:
            Input:""Polyamides **P4,** **P6,** **P8,** **P10,and** **P12** were syn-thesized by interfacial polycondensation $\mathrm {n}^{6}$ of
                    **Table II Thermal Properties of Polyamides**
                    | Polymer | $T_{g}{}^{\mathrm {a}}\left({}^{\circ }\mathrm {C}\right)$ | $T_{d}{}^{\mathrm {c}}\left({}^{\circ }\mathrm {C}\right)$ |
                    | --- | --- | --- |
                    | P4 | b | 451 |
                    | P6 | 201 | 458 |
                    | P8 | 185 | 459 |
                    | P10 | 166 | 459 |
                    | P12 | 154 | 461 |
                    "Glass transition temperature, observed by DSC in a ni-trogen atmosphere.
                    bNot observed.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | P4 | Nan |
            | P6 | 201°C |
            | P8 | 185°C |
            | P10 | 166°C |
            | P12 | 154°C |

            Example 2:
            Input:"" <!-- PAI GAS TRANSPORT PROPERTIES 2185 -->
                    Table II.Structural and Physical Parameters of $\text {PAIs}^{\mathrm {a}}$ 
                    | Sample | $\begin{array}{c}T_{g}\\ (\mathrm {\sim K})\end{array}$ | r<br>$\left(\mathrm {kg}/\mathrm {m}^{3}\right)$ | $<p>$(nm) | $\left\langle d_{0}\right\rangle$(nm) | FFV | $E_{\mathrm {coh}}$(kJ/mol) |
                    | --- | --- | --- | --- | --- | --- | --- |
                    | PAI(TMI/DPA) | 540 | 1.3012 | 1.18 | 0.55 | 0.1278 | 198.63 |
                    | PAI(TMI/HEA) | 510 | 1.3205 | 1.04 | 0.53 | 0.1298 | 232.33 |
                    | PAI(TMI/TFA) | 527 | 1.4301 | 1.06 | 0.52 | 0.1459 | 273.09 |
                    | PAI(TMI/CDA) | 618 | 1.2581 | 1.60 | 0.60 | 0.1499 | 259.04 |
                    | PAI(PMI/CDA) | 623 | 1.2864 | 1.15 | 0.62 | 0.1551 | 281.23 |
                    a glass transition temperature; $ρ,$  density ( $\left.T=23^{\circ }\mathrm {C}\right);$  ^p&, persistence length; $\left\langle d_{0}\right\rangle ,$  inter-chain distance; FFV, fractional free $T_{g},$ volume $\left(T=23^{\circ }\mathrm {C}\right);E_{\mathrm {coh}}$  molar cohesive energy density.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | PAI(TMI/DPA) | 540K |
            | PAI(TMI/HEA) | 510K |
            | PAI(TMI/TFA) | 527K |
            | PAI(TMI/CDA) | 618K |
            | PAI(PMI/CDA) | 623K |

            Example 3:
            input:"" The diphenolic monomers were prepared using minor modifications of previously published procedures.11 Briefly, each tyrosine alkyl ester was coupled with recrystallized
            3-(4-hydroxyphenyl)-propionic acid (or in some cases, 4-hydroxyphenylacetic acid) using EDCI (1.0 eq.) and HOBt(0.1 eq.) in a solution of either N-methylpyrrolidinone:ethyl
            acetate (1:3; 1.5M concentration of tyrosine ester) or aceto-nitrile (0.75M concentration of tyrosine ester). After aqueousworkup, rotoevaporation, and trituration in hexane, the di-
            phenolic monomers (Figs. 1 and 2) were obtained in puritiesof 96–99% [as measured by high power liquid chromatog- raphy (HPLC) peak ratios or by melting point depressionusing DSC]. Most of the diacids were commercially available in high purity and were recrystallized prior to useFibroblast proliferation was observed to be more sensitive to the chemical structure of the polymer than
            TABLE I
            Room Temperature ( $\left(22^{\circ }\mathrm {C}\right)$  Mechanical Properties of Selected Polyarylates
            | Polymer | $\mathrm {T}_{g}\left({}^{\circ }\mathrm {C}\right)$ | Young’s Modulus (GPa) | Yield Stress (MPa) | Strain at Break (%) |
            | --- | --- | --- | --- | --- |
            | Poly(DTE succinate) | 78 | $1.68\pm 0.17$ | $40.7\pm 3.2$ | $304\pm 102$ |
            | Poly(DTB succinate) | 67 | $1.56\pm 0.18$ | $44.8\pm 3.8$ | $566\pm 36$ |
            | Poly(DTE adipate) | 61 | $1.56\pm 0.10$ | $42.0\pm 4.4$ | $638\pm 152$ |
            | Poly(DTH succinate) | 53 | $1.61\pm 0.10$ | $44.8\pm 2.3$ | $456\pm 103$ |
            | Poly(DTE suberate) | 50 | $1.39\pm 0.10$ | $39.9\pm 3.7$ | $534\pm 91$ |
            | Poly(DTO succinate) | 48 | $1.41\pm 0.18$ | $41.9\pm 4.5$ | $622\pm 68$ |
            | Poly(DTB adipate) | 46 | $1.49\pm 0.22$ | $40.5\pm 3.5$ | $710\pm 96$ |
            | Poly(DTE sebacate) | 44 | $1.44\pm 0.06$ | $34.4\pm 3.1$ | $657\pm 56$ |
            | Poly(DTB suberate) | 37 | $1.24\pm 0.04$ | $31.0\pm 0.8$ | $138\pm 150$ |
            | Poly(DTB sebacate) | 30 | $0.28\pm 0.03$ | $5.8\pm 0.7$ | $744\pm 50$ |
            | Poly(DTO adipate) | 28 | $0.39\pm 0.09$ | $7.6\pm 1.8$ | $676\pm 86$ |
            <!-- STRUCTURE-PROPERTY CORRELATIONS IN COMBINATORIAL LIBRARY 73 -->""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | Poly(DTE succinate) | 78°C |
            | Poly(DTB succinate) | 67°C |
            | Poly(DTE adipate) | 61°C |
            | Poly(DTH succinate) | 53°C |
            | Poly(DTE suberate) | 50°C |
            | Poly(DTO succinate) | 48°C |
            | Poly(DTB adipate) | 46°C |
            | Poly(DTE sebacate) | 44°C |
            | Poly(DTB suberate) | 37°C |
            | Poly(DTB sebacate) | 30°C |
            | Poly(DTO adipate) | 28°C |

            I hope these examples can help you understand the question better. Thank you very much, I hope you can do a good job! 
            A:"""
     
    #client = OpenAI(api_key=api_key, base_url="https://dashscope.aliyuncs.com/compatible-mode/v1")
    client = OpenAI(api_key=api_key, base_url="https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1")
    max_retries = 3 
    retry_wait = 60  
    
    for attempt in range(max_retries):
        try:
            print('get response......')
            response = client.chat.completions.create(
                            model='glm-5',
                            messages=[{
                                "role": "system",
                                "content": """Answer the question as truthfully as possible using the provided context,
                                            and if the answer is not contained within the text below, say "Nan" """
                            },
                                {"role": "user", "content": user_heading + user_ending}],
                            extra_body={"enable_thinking":False}
                        )
            answer_str = response.choices[0].message.content
            polymer_properties_list.append(answer_str)
            print(f"Paper {str(i).zfill(3)} processed successfully.")
            break
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < max_retries - 1:  # Retry if not the last attempt
                print(f"Retrying in {retry_wait} seconds...")
                time.sleep(retry_wait)
            else:
                print("All attempts failed. Returning 'Nan'.")
                polymer_properties_list.append("Nan")

Start to analyze paper001
get response......
Paper 001 processed successfully.
Start to analyze paper002
get response......
Paper 002 processed successfully.
Start to analyze paper003
get response......
Paper 003 processed successfully.
Start to analyze paper004
get response......
Paper 004 processed successfully.
Start to analyze paper005
get response......
Paper 005 processed successfully.
Start to analyze paper006
get response......
Paper 006 processed successfully.
Start to analyze paper007
get response......
Paper 007 processed successfully.
Start to analyze paper008
get response......
Paper 008 processed successfully.
Start to analyze paper009
get response......
Paper 009 processed successfully.
Start to analyze paper010
get response......
Paper 010 processed successfully.
Start to analyze paper011
get response......
Paper 011 processed successfully.
Start to analyze paper012
get response......
Paper 012 processed successfully.
Start to analyze paper013
get response......
Paper 013 processed successfully.
Start to analyze paper014
get response......
Paper 014 processed successfully.
Start to analyze paper015
get response......
Paper 015 processed successfully.
Start to analyze paper016
get response......
Paper 016 processed successfully.
Start to analyze paper017
get response......
Paper 017 processed successfully.
Start to analyze paper018
get response......
Paper 018 processed successfully.
Start to analyze paper019
get response......
Paper 019 processed successfully.
Start to analyze paper020
get response......
Paper 020 processed successfully.
Start to analyze paper021
get response......
Paper 021 processed successfully.
Start to analyze paper022
get response......
Paper 022 processed successfully.
Start to analyze paper023
get response......
Paper 023 processed successfully.
Start to analyze paper024
get response......
Paper 024 processed successfully.
Start to analyze paper025
get response......
Paper 025 processed successfully.
Start to analyze paper026
get response......
Paper 026 processed successfully.
Start to analyze paper027
get response......
Paper 027 processed successfully.
Start to analyze paper028
get response......
Paper 028 processed successfully.
Start to analyze paper029
get response......
Paper 029 processed successfully.
Start to analyze paper030
get response......
Paper 030 processed successfully.
Start to analyze paper031
get response......
Paper 031 processed successfully.
Start to analyze paper032
get response......
Paper 032 processed successfully.
Start to analyze paper033
get response......
Paper 033 processed successfully.
Start to analyze paper034
get response......
Paper 034 processed successfully.
Start to analyze paper035
get response......
Paper 035 processed successfully.
Start to analyze paper036
get response......
Paper 036 processed successfully.
Start to analyze paper037
get response......
Paper 037 processed successfully.
Start to analyze paper038
get response......
Paper 038 processed successfully.
Start to analyze paper039
get response......
Paper 039 processed successfully.
Start to analyze paper040
get response......
Paper 040 processed successfully.
Start to analyze paper041
get response......
Paper 041 processed successfully.
Start to analyze paper042
get response......
Paper 042 processed successfully.
Start to analyze paper043
get response......
Paper 043 processed successfully.
Start to analyze paper044
get response......
Paper 044 processed successfully.
Start to analyze paper045
get response......
Paper 045 processed successfully.
Start to analyze paper046
get response......
Paper 046 processed successfully.
Start to analyze paper047
get response......
Paper 047 processed successfully.
Start to analyze paper048
get response......
Paper 048 processed successfully.
Start to analyze paper049
get response......
Paper 049 processed successfully.
Start to analyze paper050
get response......
Paper 050 processed successfully.
Start to analyze paper051
get response......
Paper 051 processed successfully.
Start to analyze paper052
get response......
Paper 052 processed successfully.
Start to analyze paper053
get response......
Paper 053 processed successfully.
Start to analyze paper054
get response......
Paper 054 processed successfully.
Start to analyze paper055
get response......
Paper 055 processed successfully.
Start to analyze paper056
get response......
Paper 056 processed successfully.
Start to analyze paper057
get response......
Paper 057 processed successfully.
Start to analyze paper058
get response......
Paper 058 processed successfully.
Start to analyze paper059
get response......
Paper 059 processed successfully.
Start to analyze paper060
get response......
Paper 060 processed successfully.
Start to analyze paper061
get response......
Paper 061 processed successfully.
Start to analyze paper062
get response......
Paper 062 processed successfully.
Start to analyze paper063
get response......
Paper 063 processed successfully.
Start to analyze paper064
get response......
Paper 064 processed successfully.
Start to analyze paper065
get response......
Paper 065 processed successfully.
Start to analyze paper066
get response......
Paper 066 processed successfully.
Start to analyze paper067
get response......
Paper 067 processed successfully.
Start to analyze paper068
get response......
Paper 068 processed successfully.
Start to analyze paper069
get response......
Paper 069 processed successfully.
Start to analyze paper070
get response......
Paper 070 processed successfully.
Start to analyze paper071
get response......
Paper 071 processed successfully.
Start to analyze paper072
get response......
Paper 072 processed successfully.
Start to analyze paper073
get response......
Paper 073 processed successfully.
Start to analyze paper074
get response......
Paper 074 processed successfully.
Start to analyze paper075
get response......
Paper 075 processed successfully.
Start to analyze paper076
get response......
Paper 076 processed successfully.
Start to analyze paper077
get response......
Paper 077 processed successfully.
Start to analyze paper078
get response......
Paper 078 processed successfully.
Start to analyze paper079
get response......
Paper 079 processed successfully.
Start to analyze paper080
get response......
Paper 080 processed successfully.
Start to analyze paper081
get response......
Paper 081 processed successfully.
Start to analyze paper082
get response......
Paper 082 processed successfully.
Start to analyze paper083
get response......
Paper 083 processed successfully.
Start to analyze paper084
get response......
Paper 084 processed successfully.
Start to analyze paper085
get response......
Paper 085 processed successfully.
Start to analyze paper086
get response......
Paper 086 processed successfully.
Start to analyze paper087
get response......
Paper 087 processed successfully.
Start to analyze paper088
get response......
Paper 088 processed successfully.
Start to analyze paper089
get response......
Paper 089 processed successfully.
Start to analyze paper090
get response......
Paper 090 processed successfully.
Start to analyze paper091
get response......
Paper 091 processed successfully.
Start to analyze paper092
get response......
Paper 092 processed successfully.
Start to analyze paper093
get response......
Paper 093 processed successfully.
Start to analyze paper094
get response......
Paper 094 processed successfully.
Start to analyze paper095
get response......
Paper 095 processed successfully.
Start to analyze paper096
get response......
Paper 096 processed successfully.
Start to analyze paper097
get response......
Paper 097 processed successfully.
Start to analyze paper098
get response......
Paper 098 processed successfully.
Start to analyze paper099
get response......
Paper 099 processed successfully.
Start to analyze paper100
get response......
Paper 100 processed successfully.
Start to analyze paper101
get response......
Paper 101 processed successfully.
Start to analyze paper102
get response......
Paper 102 processed successfully.
Start to analyze paper103
get response......
Paper 103 processed successfully.
Start to analyze paper104
get response......
Paper 104 processed successfully.
Start to analyze paper105
get response......
Paper 105 processed successfully.
Start to analyze paper106
get response......
Paper 106 processed successfully.
Start to analyze paper107
get response......
Paper 107 processed successfully.
Start to analyze paper108
get response......
Paper 108 processed successfully.
Start to analyze paper109
get response......
Paper 109 processed successfully.
Start to analyze paper110
get response......
Paper 110 processed successfully.
Start to analyze paper111
get response......
Paper 111 processed successfully.
Start to analyze paper112
get response......
Paper 112 processed successfully.
Start to analyze paper113
get response......
Paper 113 processed successfully.
Start to analyze paper114
get response......
Paper 114 processed successfully.
Start to analyze paper115
get response......
Paper 115 processed successfully.
Start to analyze paper116
get response......
Paper 116 processed successfully.
Start to analyze paper117
get response......
Paper 117 processed successfully.
Start to analyze paper118
get response......
Paper 118 processed successfully.
Start to analyze paper119
get response......
Paper 119 processed successfully.
Start to analyze paper120
get response......
Paper 120 processed successfully.
Start to analyze paper121
get response......
Paper 121 processed successfully.
Start to analyze paper122
get response......
Paper 122 processed successfully.
Start to analyze paper123
get response......
Paper 123 processed successfully.
Start to analyze paper124
get response......
Paper 124 processed successfully.
Start to analyze paper125
get response......
Paper 125 processed successfully.
Start to analyze paper126
get response......
Paper 126 processed successfully.
Start to analyze paper127
get response......
Paper 127 processed successfully.
Start to analyze paper128
get response......
Paper 128 processed successfully.
Start to analyze paper129
get response......
Paper 129 processed successfully.
Start to analyze paper130
get response......
Paper 130 processed successfully.
Start to analyze paper131
get response......
Paper 131 processed successfully.
Start to analyze paper132
get response......
Paper 132 processed successfully.
Start to analyze paper133
get response......
Paper 133 processed successfully.
Start to analyze paper134
get response......
Paper 134 processed successfully.
Start to analyze paper135
get response......
Paper 135 processed successfully.
Start to analyze paper136
get response......
Paper 136 processed successfully.
Start to analyze paper137
get response......
Paper 137 processed successfully.
Start to analyze paper138
get response......
Paper 138 processed successfully.
Start to analyze paper139
get response......
Paper 139 processed successfully.
Start to analyze paper140
get response......
Paper 140 processed successfully.
Start to analyze paper141
get response......
Paper 141 processed successfully.
Start to analyze paper142
get response......
Paper 142 processed successfully.
Start to analyze paper143
get response......
Paper 143 processed successfully.
Start to analyze paper144
get response......
Paper 144 processed successfully.
Start to analyze paper145
get response......
Paper 145 processed successfully.
Start to analyze paper146
get response......
Paper 146 processed successfully.
Start to analyze paper147
get response......
Attempt 1 failed: Error code: 400 - {'error': {'code': 'data_inspection_failed', 'param': None, 'message': 'Input text data may contain inappropriate content.', 'type': 'data_inspection_failed'}, 'id': 'chatcmpl-95c7ceb7-b2a3-4e14-a332-4ec993be76ee'}
Retrying in 60 seconds...
get response......
Attempt 2 failed: Error code: 400 - {'error': {'code': 'data_inspection_failed', 'param': None, 'message': 'Input text data may contain inappropriate content.', 'type': 'data_inspection_failed'}, 'id': 'chatcmpl-c790449e-c044-4ad0-a8e4-ca472429c6d4'}
Retrying in 60 seconds...
get response......
Attempt 3 failed: Error code: 400 - {'error': {'code': 'data_inspection_failed', 'param': None, 'message': 'Input text data may contain inappropriate content.', 'type': 'data_inspection_failed'}, 'id': 'chatcmpl-0787d8ca-507f-44d2-8441-9a6b557189f2'}
All attempts failed. Returning 'Nan'.
Start to analyze paper148
get response......
Paper 148 processed successfully.
Start to analyze paper149
get response......
Paper 149 processed successfully.
Start to analyze paper150
get response......
Paper 150 processed successfully.
Start to analyze paper151
get response......
Paper 151 processed successfully.
Start to analyze paper152
get response......
Paper 152 processed successfully.
Start to analyze paper153
get response......
Paper 153 processed successfully.
Start to analyze paper154
get response......
Paper 154 processed successfully.
Start to analyze paper155
get response......
Paper 155 processed successfully.
Start to analyze paper156
get response......
Paper 156 processed successfully.
Start to analyze paper157
get response......
Paper 157 processed successfully.
Start to analyze paper158
get response......
Paper 158 processed successfully.
Start to analyze paper159
get response......
Paper 159 processed successfully.
Start to analyze paper160
get response......
Paper 160 processed successfully.
Start to analyze paper161
get response......
Paper 161 processed successfully.
Start to analyze paper162
get response......
Paper 162 processed successfully.
Start to analyze paper163
get response......
Paper 163 processed successfully.
Start to analyze paper164
get response......
Paper 164 processed successfully.
Start to analyze paper165
get response......
Paper 165 processed successfully.
Start to analyze paper166
get response......
Paper 166 processed successfully.
Start to analyze paper167
get response......
Paper 167 processed successfully.
Start to analyze paper168
get response......
Paper 168 processed successfully.
Start to analyze paper169
get response......
Paper 169 processed successfully.
Start to analyze paper170
get response......
Paper 170 processed successfully.
Start to analyze paper171
get response......
Paper 171 processed successfully.
Start to analyze paper172
get response......
Paper 172 processed successfully.
Start to analyze paper173
get response......
Paper 173 processed successfully.
Start to analyze paper174
get response......
Paper 174 processed successfully.
Start to analyze paper175
get response......
Paper 175 processed successfully.
Start to analyze paper176
get response......
Paper 176 processed successfully.
Start to analyze paper177
get response......
Paper 177 processed successfully.
Start to analyze paper178
get response......
Paper 178 processed successfully.
Start to analyze paper179
get response......
Paper 179 processed successfully.
Start to analyze paper180
get response......
Paper 180 processed successfully.
Start to analyze paper181
get response......
Paper 181 processed successfully.
Start to analyze paper182
get response......
Paper 182 processed successfully.
Start to analyze paper183
get response......
Paper 183 processed successfully.
Start to analyze paper184
get response......
Paper 184 processed successfully.
Start to analyze paper185
get response......
Paper 185 processed successfully.
Start to analyze paper186
get response......
Paper 186 processed successfully.
Start to analyze paper187
get response......
Paper 187 processed successfully.
Start to analyze paper188
get response......
Paper 188 processed successfully.
Start to analyze paper189
get response......
Paper 189 processed successfully.
Start to analyze paper190
get response......
Paper 190 processed successfully.
Start to analyze paper191
get response......
Paper 191 processed successfully.
Start to analyze paper192
get response......
Paper 192 processed successfully.
Start to analyze paper193
get response......
Paper 193 processed successfully.
Start to analyze paper194
get response......
Paper 194 processed successfully.
Start to analyze paper195
get response......
Paper 195 processed successfully.
Start to analyze paper196
get response......
Paper 196 processed successfully.
Start to analyze paper197
get response......
Paper 197 processed successfully.
Start to analyze paper198
get response......
Paper 198 processed successfully.
Start to analyze paper199
get response......
Paper 199 processed successfully.
Start to analyze paper200
get response......
Paper 200 processed successfully.
Start to analyze paper201
get response......
Paper 201 processed successfully.
Start to analyze paper202
get response......
Paper 202 processed successfully.
Start to analyze paper203
get response......
Paper 203 processed successfully.
Start to analyze paper204
get response......
Paper 204 processed successfully.
Start to analyze paper205
get response......
Paper 205 processed successfully.
Start to analyze paper206
get response......
Paper 206 processed successfully.
Start to analyze paper207
get response......
Paper 207 processed successfully.
Start to analyze paper208
get response......
Paper 208 processed successfully.
Start to analyze paper209
get response......
Paper 209 processed successfully.
Start to analyze paper210
get response......
Paper 210 processed successfully.
Start to analyze paper211
get response......
Paper 211 processed successfully.
Start to analyze paper212
get response......
Paper 212 processed successfully.
Start to analyze paper213
get response......
Paper 213 processed successfully.
Start to analyze paper214
get response......
Paper 214 processed successfully.
Start to analyze paper215
get response......
Paper 215 processed successfully.
Start to analyze paper216
get response......
Paper 216 processed successfully.
Start to analyze paper217
get response......
Paper 217 processed successfully.
Start to analyze paper218
get response......
Paper 218 processed successfully.
Start to analyze paper219
get response......
Paper 219 processed successfully.
Start to analyze paper220
get response......
Paper 220 processed successfully.
Start to analyze paper221
get response......
Paper 221 processed successfully.
Start to analyze paper222
get response......
Paper 222 processed successfully.
Start to analyze paper223
get response......
Paper 223 processed successfully.
Start to analyze paper224
get response......
Paper 224 processed successfully.
Start to analyze paper225
get response......
Paper 225 processed successfully.
Start to analyze paper226
get response......
Paper 226 processed successfully.
Start to analyze paper227
get response......
Paper 227 processed successfully.
Start to analyze paper228
get response......
Paper 228 processed successfully.
Start to analyze paper229
get response......
Paper 229 processed successfully.
Start to analyze paper230
get response......
Paper 230 processed successfully.
Start to analyze paper231
get response......
Paper 231 processed successfully.
Start to analyze paper232
get response......
Paper 232 processed successfully.
Start to analyze paper233
get response......
Paper 233 processed successfully.
Start to analyze paper234
get response......
Paper 234 processed successfully.
Start to analyze paper235
get response......
Paper 235 processed successfully.
Start to analyze paper236
get response......
Paper 236 processed successfully.
Start to analyze paper237
get response......
Paper 237 processed successfully.
Start to analyze paper238
get response......
Paper 238 processed successfully.
Start to analyze paper239
get response......
Paper 239 processed successfully.
Start to analyze paper240
get response......
Paper 240 processed successfully.
Start to analyze paper241
get response......
Paper 241 processed successfully.
Start to analyze paper242
get response......
Paper 242 processed successfully.
Start to analyze paper243

In [4]:
import pickle
with open('polymer_properties_list_GLM5(1_580).pkl', 'wb') as f:
    pickle.dump(polymer_properties_list, f)

In [5]:
import pickle
with open('polymer_properties_list_GLM5(1_580).pkl', 'rb') as f:
    loaded_list_0_580 = pickle.load(f)

In [7]:
import io
import re
import pandas as pd

def parse_loaded_list_to_df(loaded_list, start_id):
    all_dataframes = []

    for index, answer_str in enumerate(loaded_list, start=start_id):
        # 改进后的正则：允许最后一行无换行
        table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
        if table_match:
            table_str = table_match[0]

            # 去掉每行两边的 |，避免 read_csv 产生空列
            table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

            data_io = io.StringIO(table_str)
            try:
                df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
                df.columns = df.columns.str.strip()
                df = df.dropna(how="all")
                df = df.reset_index(drop=True)
                df["ID"] = index
                all_dataframes.append(df)
            except Exception as e:
                print(f"Error parsing entry {index}: {e}")
        else:
            print(f"No table found in entry {index}")

    combined_df = pd.concat(all_dataframes, ignore_index=True)

    return combined_df

df_GLM5_0_580 = parse_loaded_list_to_df(
    loaded_list_0_580,
    start_id=1
)

No table found in entry 147

In [8]:
df_GLM5_0_580 = df_GLM5_0_580[~df_GLM5_0_580.apply(lambda row: row.astype(str).str.contains('---').any(), axis=1)]
df_cleaned = df_GLM5_0_580[~df_GLM5_0_580.apply(lambda row: row.astype(str).str.contains('--').any(), axis=1)]
def remove_temp_unit(x):
    try:
        if 'K' in str(x):
            return float(str(x).replace('K', ''))
        elif '°C' in str(x):
            return float(str(x).replace('°C', ''))
        else:
            return x
    except ValueError:
        return x

df_cleaned['Glass transition temperature'] = df_cleaned['Glass transition temperature'].apply(remove_temp_unit)
df_cleaned=df_cleaned.reset_index(drop=True)
df_cleaned

     Polyamide name Glass transition temperature   ID
0               Va                         258.0    1
1               Vb                         262.0    1
2               Vi                         256.0    1
3              VIa                         258.0    1
4              VIc                         270.0    1
...             ...                          ...  ...
3026         PA 46                          78.0  578
3027         PA 66                          65.0  578
3028          PA 6                          58.0  578
3029          PA 6                         315.3  579
3030       Nylon 6                      60~70°C   580

[3031 rows x 3 columns]

In [9]:
df_cleaned.to_excel('PA_glm5_extraction.xlsx', index=False)

### GPT 5.4

In [ ]:
from openai import OpenAI
api_key = 'xxxxxxxx' # Replace 'xxxxxxxx' with your actual OpenAI API key

In [12]:
import pandas as pd
import os
for i in range(1, 2):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
text

Start to analyze paper001

"# Preparation of Poly(amide-imide)s Derived from Biphenyltetracarboxylic Dianhydrides\n\nAKINORI SHIOTANI, $ ^{1} $  MASAFUMI KOHDA $ ^{1} $\n\n¹Chiba Research Laboratory, UBE Industries Ltd., 8-1 Goi-Minamikaigan, Ichihara city, CHIBA, 290 Japan\n\nReceived 25 April 1996; accepted 25 April 1996\n\nABSTRACT: Four new diimide-dicarboxylic acids (I–IV) were prepared by condensation of s- or a-BPDA with para- or meta-aminobenzoic acid. A series of aromatic poly(amideimide)s containing these diimide-dicarboxylic units was prepared by three methods: (1) acid chloride method, (2) triphenylphosphite method, and (3) one-pot method. A typical polymer of the series is readily soluble in polar aprotic solvents such as N-methyl-2-pyrrolidone (NMP), dimethylsulfoxide (DMSO), and pyridine (py) and could be cast into tough and flexible films. These were characterized by inherent viscosity, differential scanning calorimetry (DSC), and thermogravimetric analysis (TGA) measurements. The glass transition temperatures of these polymers were in the range of 220–290°C, and the 5% weight loss temperatures were 450–500°C. Films prepared by casting from polymer solutions exhibited good tensile properties. © 1997 John Wiley & Sons, Inc. J Appl Polym Sci 63: 865–873, 1997\n\nKey words: poly(amide-imide)s; 3,3',4,4'-biphenyltetracarboxylic dianhydride; 2,3,3',4'-biphenyltetracarboxylic dianhydride; p-aminobenzoic acid; m-aminobenzoic acid; polycondensation\n\n# INTRODUCTION\n\nAromatic polyimides (PIs) are well known as high-temperature, resistant materials and have been widely used in aerospace and microelectronics industries. $ ^{1,2} $  Kapton $ ^{\\circledR} $  (poly(4,4'-oxydiphenylene pyromellitimide) has been commercialized by DuPont Co. in the 1960s. We have developed a method of production for biphenyltetracarboxylic dianhydride (BPDA) $ ^{3,4} $  and put a new polyimide Upilex $ ^{\\circledR} $  on the market in 1982. Wholly aromatic polyimides are absolutely infusible; thus, the two-step process is generally utilized for the production of polyimides. Aromatic poly(amide-imide) (PAIs) are more readily processed by the injection molding or extrusion technique. PAIs are important engineering plastics due to their excellent mechanical properties, high thermal stability, and improved processability, in particular, as\n\ncompared with PIs. A number of PAIs have been previously described: (1) PAI from trimellitic anhydride with diamines, $ ^{6} $  (2) PAI from monoimide-dicarboxylic acids with diamines, $ ^{7-9} $  (3) PAI from diimide-dicarboxylic acids with diamines, $ ^{10-27} $  (4) PAI from diimide-diamines with dicarboxylic acids, $ ^{28} $  and (5) PAI by the Pd-catalyzed carbonylation of aromatic dihalides containing an imide-skeleton with diamines. $ ^{29,30} $\n\nIn this contribution, we wish to report the preparation of new diimide-dicarboxylic acids derived from BPDA and a number of PAIs therefrom.\n\n# EXPERIMENTAL\n\n# Materials\n\n3,3',4,4'-biphenyltetracarboxylic dianhydride (s-BPDA) and 2,3,3',4'-biphenyltetracarboxylic dianhydride (a-BPDA) are products of UBE Industries Ltd. Other chemicals were commercially available. Aromatic diamines used were\n\n$  \\text{H}_2\\text{N-Ar-NH}_2 =  $\n\na (BAPS)\n\n***Nc1ccc(Oc2ccc(S(=O)(=O)c3ccc(Oc4ccc(N)cc4)cc3)cc2)cc1***\n\nb (BAPS-M)\n\n***Nc1cccc(Oc2ccc(S(=O)(=O)c3ccc(Oc4cccc(N)c4)cc3)cc2)c1***\n\nc (BAPB)\n\n***Nc1ccc(Oc2ccc(-c3ccc(Oc4ccc(N)cc4)cc3)cc2)cc1***\n\nd (BAPE)\n\n***Nc1ccc(Oc2ccc(Oc3ccc(Oc4ccc(N)cc4)cc3)cc2)cc1***\n\ne (BAPP)\n\n***CC(C)(c1ccc(Oc2ccc(N)cc2)cc1)c1ccc(Oc2ccc(N)cc2)cc1***\n\nf (TPE-Q)\n\n***Nc1ccc(Oc2ccc(Oc3ccc(N)cc3)cc2)cc1***\n\ng (TPE-R)\n\n***Nc1ccc(Oc2cccc(Oc3ccc(N)cc3)c2)cc1***\n\nh (DADE)\n\n***Nc1ccc(Oc2ccc(N)cc2)cc1***\n\ni (3,3'-DADS)\n\n***Nc1cccc(S(=O)(=O)c2cccc(N)c2)c1***\n\nj (PPD)\n\n***Nc1ccc(N)cc1***\n\nFigure 1 Diamines used in the polycondensation.\n\nbis[4-(4-aminophenoxy)phenyl]sulfone (BAPS), bis[4-(3-aminophenoxy)phenyl]sulfone (BAPS-M), 4,4'-bis(4-aminophenoxy)biphenyl (BAPB), 4,4'-bis(4-aminophenoxy)biphenylether (BAPE), 2,2-bis(4-aminophenoxy)benzene (TPE-Q), 1,3-bis(4-aminophenoxy)benzene (TPE-R), 4,4'-diaminodiphenylether (DADE), 3,3'-diaminodiphenylsulfone (3,3'-DADS), and p-phenylenediamine (PPD). These diamines, as shown by their formulae in Figure 1, were used without further purification. N-Methyl-2-pyrrolidone (NMP) was purified by distillation under reduced pressure. Pyridine (py), thionyl chloride, and toluene were distilled prior to use.\n\nDiimide-dicarboxylic acids (DIDAs) were prepared by condensation of s- or a-BPDA with para- or meta-aminobenzoic acid under nitrogen. The synthesis of N,N'-bis(4-carboxyphenyl)-biphenyl-3,3',4,4'-tetracarboxydiimide (I) serves to illustrate the method. The reaction vessel was a 500 mL three-necked round flask equipped with a mechanical stirrer, a water separating trap topped by a condenser, and a nitrogen inlet. In a typical experiment, p-amino-benzoic acid (27.43 g, 0.20M) in 300 mL of NMP was combined with s-BPDA (29.42 g, 0.10M) at room temperature. The mixture was heated to 100°C to afford a homogeneous solution within 0.5 h. 50 mL of toluene was added, and the reaction was completed under reflux for 4 h, removing the water azeotropically. After the first 40 minutes, a light yellow product began to precipitate from the reaction mixture. On standing overnight at room temperature, the product was filtered, washed with 500 mL of acetone, and dried in vacuum at 120°C for 3 h.\n\nyield of I was 50.61 g (95%); mp = 444°C (by DSC). IR (KBr disc.) was 1778 (imide C=O), 1732 (imide C=O), 1373 (imide ring C—N), and 754 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. calcd: for C₃₀H₁₆N₂O₈ was as follows: C, 67.67; H, 3.03; N, 5.26. Found was as follows: C, 67.9; H, 3.3; N, 5.3. N,N'-bis(3-carboxyphenyl)-biphenyl-3,3',4,4'-tetracarboxydiimide (II), N,N'-bis(4-carboxyphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (III), and N,N'-bis(3-carboxyphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (IV) were prepared accordingly.\n\nII: yield was 91%; mp = 426°C (by DSC). IR (KBr disc.) was 1776 (imide C=O), 1730 and 1722 (imide C=O), 1379 (imide ring C—N), and 758 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. found: C, 67.9; H, 3.3; N, 5.3.\n\nIII: yield was 88%; mp = 414°C (by DSC). IR (KBr disc.): 1776 (imide C=O), 1720 (imide C=O), 1375 (imide ring C—N), and 762 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. found: C, 67.2; H, 2.8; N, 5.2.\n\nIV: yield was 80%; mp = 423°C (by DSC). IR (KBr disc.): 1768 (imide C=O), 1716 (imide C=O), 1375 (imide ring C—N), and 754 (imide ring deformation). FD-MS: m/z = 532 (M⁺). Anal. found: C, 67.2; H, 2.8; N, 5.1. Diimide-dicarboxylic acid dichlorides (DIDA-Cl) were synthesized by the chlorination of DIDA with excess thionyl chloride. As a typical procedure, the synthesis of N,N'-bis(4-chlorocarbonylphenyl)-biphenyl-3,3',4,4'-tetra-carboxydiimide (I-Cl) is given as follows: In a 300 mL round flask, a mixture of I (5.00 g), thionyl chloride (150 mL), and three drops of dimethylformamide as a catalyst was heated under reflux for 6 h. On standing overnight, thionyl chloride\n\nwas distilled off; and the product was washed two times with 30 mL of dry toluene, filtered, and dried in vacuum at 80°C for 6 h. Yield was 5.23 g (98%). Anal. calcd. for C₃₀H₁₄N₂O₆Cl₂: C, 63.29; H, 2.45; N, 4.92; Cl, 12.45. Found: C, 63.4; H, 2.5; N, 4.9; Cl, 12.6. N,N'-bis(3-chlorocarbonylphenyl)-biphenyl-3,3',4,4'-tetracarboxydiimide (II-Cl), N,N'-bis(4-chlorocarbonylphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (III-Cl), and N,N'-bis(3-chlorocarbonylphenyl)-biphenyl-2,3,3',4'-tetracarboxydiimide (IV-Cl) were prepared accordingly.\n\nII-Cl: yield was 99%. Anal. found: C, 63.3; H, 2.5; N, 4.9; Cl, 12.5. III-Cl: yield was 99%, Anal. found: C, 63.5; H, 2.6; N, 4.8; Cl, 12.6. IV-Cl: yield was 98%, Anal. found: C, 62.3; H, 2.6; N, 5.0; Cl, 12.6.\n\n# Polycondensation\n\n# Acid Chloride Method\n\nAs a typical experiment, the polycondensation of II-Cl with BAPS under nitrogen was conducted as follows. In a 100 mL four-necked round flask equipped with a mechanical stirrer, a condenser, a dropping funnel, and a nitrogen inlet were combined II-Cl (1.423 g, 2.5mM), NMP (15 mL), and pyridine (0.5 mL). A solution containing BAPS (1.081 g, 2.5mM) and NMP (5 mL) was added through a funnel into the reaction mixture at 60°C within 15 min. The funnel was washed with an additional 3 mL of NMP. After several minutes, a polymerization started, and the reaction temperature was maintained at 60°C for 100 min in an oil bath. The resulting viscous solution was poured into 1 L of water under rapid stirring, and the product precipitated was pulverized with a cooking mixer. The product was washed with 0.5 L of water and 0.5 L of methanol and dried in vacuum at 120°C for 3 h. Yield was 2.219 g (96%).\n\n# Triphenyl Phosphate Method\n\nAs a typical procedure, the polycondensation of IV with TPE-Q is described. Using the identical equipment IV (1.331 g, 2.5mM), TPE-Q (0.731 g, 2.5mM), CaCl₂ (1.2 g), NMP (20 mL), pyridine (4 mL), and P(OPh)₃ (1.5 mL) were combined. The reaction mixture was heated to 150°C to afford a clear solution within 5 min. The reaction temperature was maintained at 150°C for 3 h. The resulting viscous solution was treated as aforementioned. Yield was 1.873 g (95%).\n\n# One-Pot Method\n\nAs a typical example, the polycondensation of s-BPDA and m-ABA with DADE is given. In a 100\n\nmL three-necked round flask, m-aminobenzoic acid (0.686 g, 5.0 mM) in 7 mL of anhydrous NMP under nitrogen was combined with s-BPDA (0.736 g, 2.5 mM) at room temperature. The mixture was heated to 100°C to afford a homogeneous solution within 0.5 h. Addition of 6 mL of toluene after 20 min induced precipitation of a light yellow product. To remove water azeotropically, the reaction mixture was kept under reflux for 4 h. After cooling to room temperature and removing the water separating trap, DADE (0.511 g, 2.55 mM), CaCl₂ (1.2 g), NMP (14 mL), pyridine (4 mL), and P(OPh)₃ (1.5 mL) were added to the mixture, which was heated to 150°C to afford a clear solution within 5 min. After 3 h, at 150°C, a viscous solution resulted, which was treated as aforementioned. Yield was 1.707 g (98%).\n\n# Measurements\n\nThe films used for the thermal measurements were prepared by casting NMP solutions containing 20% polymer by weight onto a glass plate and drying at 80°C for 30 min, 80–170°C for 30 min, 200°C for 30 min, 200–300°C for 15 min, and 300°C for 30 min.\n\nDifferential scanning calorimetry (DSC) measurements were conducted on a Seiko-Denshi DS2000 instrument in aluminium pans at a heating rate of 20°C/min under nitrogen. Glass transition temperatures ( $ T_g $ s) were determined from the DSC curves.  $ T_g $ s of polymers VII (Table IV) could not be unambiguously determined from the DSC measurements. Thermogravimetric measurements (TGA) were conducted at a heating rate of 10°C/min under nitrogen. The 5% weight loss temperatures ( $ T_d^5 $ s) were determined from the TGA curve. Inherent viscosities were measured with a Cannon Fenske viscosimeter in NMP solution (0.5 g/dL, 30°C). Infrared spectra were recorded on a Nihondenshi JIR-5500 Fourier transform infrared (FTIR) spectrometer. Test pieces (6 cm long, 0.4 mm wide, and 0.02 mm thick) for mechanical measurements were prepared by a casting method, as described above, and the tensile data were obtained according to the ASTM D882 standard.\n\n# RESULTS AND DISCUSSION\n\n# Monomer Synthesis\n\nFour novel diimide-dicarboxylic acids (I–IV) have been prepared by condensation of s- or a-\n\nTable I Conditions for the Acid Chloride Method and Inherent Viscosities of PAIs $ ^{a} $\n\n| Polymer   | DIDA   | Diamine   | Polycondensation   | Polycondensation   | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n|:----------|:-------|:----------|:-------------------|:-------------------|:------------|:------------------------------------------|\n| Polymer   | DIDA   | Diamine   | Temp. (°C)         | Time (min)         | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n| Va        | I      | a         | 70                 | 95                 | 97          | 1.34                                      |\n| Vb        |        | b         | 70                 | 105                | 93          | 1.35                                      |\n| Ve        |        | e         | 70                 | 180                | 95          | 1.64                                      |\n| Vi        |        | i         | 70                 | 60                 | 90          | 1.17                                      |\n| VIa       | II     | a         | 60                 | 100                | 91          | 0.83                                      |\n| VIc       |        | c         | 60                 | 65                 | 82          | 0.84                                      |\n| VId       |        | d         | 60                 | 65                 | 84          | 0.73                                      |\n| VIe       |        | e         | 60                 | 180                | 92          | 0.50                                      |\n| VIf       |        | f         | 60                 | 65                 | 86          | 1.04                                      |\n| VIg       |        | g         | 60                 | 180                | 94          | 0.81                                      |\n| VIh       |        | h         | 80                 | 180                | 94          | 0.89                                      |\n| VIi       |        | i         | 60                 | 80                 | 89          | 0.36                                      |\n| VIIa      | III    | a         | 65                 | 90                 | 84          | 1.17                                      |\n| VIIb      |        | b         | 60                 | 100                | 90          | 0.99                                      |\n| VIIc      |        | c         | 60                 | 120                | 85          | 1.01                                      |\n| VIIf      |        | f         | 65                 | 30                 | 87          | 1.47                                      |\n| VIIIh     |        | h         | 60                 | 25                 | 77          | 1.35                                      |\n| VIII      |        | i         | 60                 | 180                | 78          | 0.52                                      |\n\nReaction condition: 2.5 mmol of each monomer; 0.5 mL of pyridine; monomer concentration = ca. 10 wt % in NMP.\n\n$ ^{b} $  Inherent viscosity in NMP of 0.5 g/L at 30°C.\n\nTable II Conditions for the Triphenyl Phosphate Method and Inherent Viscosities of PAIs $ ^{a} $\n\n| Polymer   | DIDA   | Diamine   | Molar Ratio (DIDA : diamine)   | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n|:----------|:-------|:----------|:-------------------------------|:------------|:------------------------------------------|\n| VIIIa     | IV     | a         | 1 : 1                          | 98          | 0.57                                      |\n| VIIIc     |        | c         | 1 : 1                          | 96          | 1.16                                      |\n| VIIId     |        | d         | 1 : 1                          | 91          | 0.54                                      |\n| VIIIe     |        | e         | 1 : 1                          | 94          | 0.80                                      |\n| VIIIf     |        | f         | 1 : 1                          | 95          | 0.92                                      |\n| VIIIg     |        | g         | 1 : 1                          | 95          | 0.88                                      |\n| VIIIh     |        | h         | 1 : 1                          | 97          | 0.84                                      |\n| VIIIi     |        | i         | 1 : 1                          | 94          | 0.39                                      |\n| VIIIj     |        | j         | 1 : 1                          | 95          | 0.76                                      |\n| VIc       | II     | c         | 1.00 : 1.02                    | 97          | 0.71                                      |\n| VId       |        | d         | 1.00 : 1.02                    | 97          | 0.57                                      |\n| VIf       |        | f         | 1.00 : 1.02                    | 98          | 0.72                                      |\n| VIg       |        | g         | 1.00 : 1.02                    | 96          | 0.69                                      |\n| VIi       |        | i         | 1.00 : 1.02                    | 98          | 0.37                                      |\n| VIj       |        | j         | 1.00 : 1.02                    | 96          | 0.76                                      |\n| VIIa      | III    | a         | 1.00 : 1.02                    | 95          | 0.58                                      |\n| VIIc      |        | c         | 1.00 : 1.02                    | 93          | 0.60                                      |\n| VIIf      |        | f         | 1.00 : 1.02                    | 95          | 0.51                                      |\n| VIIh      |        | h         | 1.00 : 1.02                    | 97          | 0.65                                      |\n\n$ ^{a} $  Reaction condition: 2.5 mmol of DIDA and 2.5 (or 2.55) mmol of diamine, 1.5 mL of triphenyl phosphite, 1.2 g of calcium chloride, 4 mL of pyridine in 20 mL of NMP, at 150°C for 3 h.\n\n$ ^{b} $ Inherent viscosity in NMP of 0.5 g/L, at 30°C.\n\nable III Conditions for the One-pot Method and Inherent Viscosities of PAIs $ ^{a} $\n\n| Polymer   | BPDA   | ABA   | Diamine   | Yield (%)   | $ \\eta_{\\text{inh}}^{\\text{b}} $ (dL/g)   |\n|:----------|:-------|:------|:----------|:------------|:------------------------------------------|\n| VIa       | s-     | m-    | a         | 91          | 0.51                                      |\n| VIh       | s-     | m-    | h         | 98          | 0.68                                      |\n| VIIc      | a-     | p-    | c         | 90          | 0.56                                      |\n| VIIIh     | a-     | m-    | h         | 88          | 0.50                                      |\n\n$ ^{a} $ Reaction condition: a mixture of 2.5 mmol of s- or a-BPD $ _{4} $  and 5.0 mmol of p- or m-ABA and 7 mL of NMP was refluxed for 4 h, then 2.55 mmol of diamine (molar ratio of DIDA : diamine = 1.00 : 1.02), 1.5 mL of triphenyl phosphite, 1.2 g of calcium chloride, and 4 mL of pyridine were added to the reaction mixture. The polymerization was carried out at 150°C for 3 h.\n\n$ ^{b} $  Inherent viscosity in NMP of 0.5 g/L at 30°C.\n\nBPDA with para- or meta-aminobenzoic acid (p- or m-ABA). For instance, s-BPDA was reacted with two mole equivalents of m-ABA to form an amic acid in homogeneous solution. In a subsequent cyclodehydration reaction, II was formed, which precipitated from the reaction mixture\n\nTable IV Properties of PAIs\n\n| PAI   | Solubility $ ^{a} $   | Solubility $ ^{a} $   | Solubility $ ^{a} $   | Solubility $ ^{a} $   | Solubility $ ^{a} $     | Solubility $ ^{a} $     |\n|:------|:----------------------|:----------------------|:----------------------|:----------------------|:------------------------|:------------------------|\n| PAI   | NMP                   | DMSO                  | py                    | Film $ ^{b} $         | $ T_{g} $ $ ^{c} $ (°C) | $ T_{d} $ $ ^{d} $ (°C) |\n| Va    | ○                     | △                     | ×                     | tough                 | 258                     | 485                     |\n| Vb    | ○                     | △                     | ×                     

In [ ]:
import pandas as pd
import os
import time
polymer_properties_list = []
for i in range(1, 581):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
    user_heading = text
    user_ending = """ Q: Can you summarize the following details of polyamide(PA) in a table: 
            Polyamide name, Glass transition temperature? 
            If any information is not provided or you are unsure, use "Nan". 
            Guidelines:
            1. For the Glass transition temperature (Tg), the format is xxxK or xxx°C.
            2. There may be many different polyamides in an article, so please don't leave them out and use multiple rows to express.
            3. Sometimes the polymers' names seems like nan-polyamides, but they are actually polyamides(e.g. some polyesters, polyarylates ... also contain amide bonds, and are therefore considered polyamides.), please be careful to identify them.
            4. Please only focus on the polyamide homopolymer information, don't include polyamide copolymers.
            5.  **Only output** the Markdown table. Do not include any other text, explanations, or comments. The table must start with the header: `| Polyamide name | Glass transition temperature |`.

            The table should have 2 columns:
            |Polyamide name |Glass transition temperature|

            To help you understand the question, here are some examples:
            Example 1:
            Input:""Polyamides **P4,** **P6,** **P8,** **P10,and** **P12** were syn-thesized by interfacial polycondensation $\mathrm {n}^{6}$ of
                    **Table II Thermal Properties of Polyamides**
                    | Polymer | $T_{g}{}^{\mathrm {a}}\left({}^{\circ }\mathrm {C}\right)$ | $T_{d}{}^{\mathrm {c}}\left({}^{\circ }\mathrm {C}\right)$ |
                    | --- | --- | --- |
                    | P4 | b | 451 |
                    | P6 | 201 | 458 |
                    | P8 | 185 | 459 |
                    | P10 | 166 | 459 |
                    | P12 | 154 | 461 |
                    "Glass transition temperature, observed by DSC in a ni-trogen atmosphere.
                    bNot observed.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | P4 | Nan |
            | P6 | 201°C |
            | P8 | 185°C |
            | P10 | 166°C |
            | P12 | 154°C |

            Example 2:
            Input:"" <!-- PAI GAS TRANSPORT PROPERTIES 2185 -->
                    Table II.Structural and Physical Parameters of $\text {PAIs}^{\mathrm {a}}$ 
                    | Sample | $\begin{array}{c}T_{g}\\ (\mathrm {\sim K})\end{array}$ | r<br>$\left(\mathrm {kg}/\mathrm {m}^{3}\right)$ | $<p>$(nm) | $\left\langle d_{0}\right\rangle$(nm) | FFV | $E_{\mathrm {coh}}$(kJ/mol) |
                    | --- | --- | --- | --- | --- | --- | --- |
                    | PAI(TMI/DPA) | 540 | 1.3012 | 1.18 | 0.55 | 0.1278 | 198.63 |
                    | PAI(TMI/HEA) | 510 | 1.3205 | 1.04 | 0.53 | 0.1298 | 232.33 |
                    | PAI(TMI/TFA) | 527 | 1.4301 | 1.06 | 0.52 | 0.1459 | 273.09 |
                    | PAI(TMI/CDA) | 618 | 1.2581 | 1.60 | 0.60 | 0.1499 | 259.04 |
                    | PAI(PMI/CDA) | 623 | 1.2864 | 1.15 | 0.62 | 0.1551 | 281.23 |
                    a glass transition temperature; $ρ,$  density ( $\left.T=23^{\circ }\mathrm {C}\right);$  ^p&, persistence length; $\left\langle d_{0}\right\rangle ,$  inter-chain distance; FFV, fractional free $T_{g},$ volume $\left(T=23^{\circ }\mathrm {C}\right);E_{\mathrm {coh}}$  molar cohesive energy density.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | PAI(TMI/DPA) | 540K |
            | PAI(TMI/HEA) | 510K |
            | PAI(TMI/TFA) | 527K |
            | PAI(TMI/CDA) | 618K |
            | PAI(PMI/CDA) | 623K |

            Example 3:
            input:"" The diphenolic monomers were prepared using minor modifications of previously published procedures.11 Briefly, each tyrosine alkyl ester was coupled with recrystallized
            3-(4-hydroxyphenyl)-propionic acid (or in some cases, 4-hydroxyphenylacetic acid) using EDCI (1.0 eq.) and HOBt(0.1 eq.) in a solution of either N-methylpyrrolidinone:ethyl
            acetate (1:3; 1.5M concentration of tyrosine ester) or aceto-nitrile (0.75M concentration of tyrosine ester). After aqueousworkup, rotoevaporation, and trituration in hexane, the di-
            phenolic monomers (Figs. 1 and 2) were obtained in puritiesof 96–99% [as measured by high power liquid chromatog- raphy (HPLC) peak ratios or by melting point depressionusing DSC]. Most of the diacids were commercially available in high purity and were recrystallized prior to useFibroblast proliferation was observed to be more sensitive to the chemical structure of the polymer than
            TABLE I
            Room Temperature ( $\left(22^{\circ }\mathrm {C}\right)$  Mechanical Properties of Selected Polyarylates
            | Polymer | $\mathrm {T}_{g}\left({}^{\circ }\mathrm {C}\right)$ | Young’s Modulus (GPa) | Yield Stress (MPa) | Strain at Break (%) |
            | --- | --- | --- | --- | --- |
            | Poly(DTE succinate) | 78 | $1.68\pm 0.17$ | $40.7\pm 3.2$ | $304\pm 102$ |
            | Poly(DTB succinate) | 67 | $1.56\pm 0.18$ | $44.8\pm 3.8$ | $566\pm 36$ |
            | Poly(DTE adipate) | 61 | $1.56\pm 0.10$ | $42.0\pm 4.4$ | $638\pm 152$ |
            | Poly(DTH succinate) | 53 | $1.61\pm 0.10$ | $44.8\pm 2.3$ | $456\pm 103$ |
            | Poly(DTE suberate) | 50 | $1.39\pm 0.10$ | $39.9\pm 3.7$ | $534\pm 91$ |
            | Poly(DTO succinate) | 48 | $1.41\pm 0.18$ | $41.9\pm 4.5$ | $622\pm 68$ |
            | Poly(DTB adipate) | 46 | $1.49\pm 0.22$ | $40.5\pm 3.5$ | $710\pm 96$ |
            | Poly(DTE sebacate) | 44 | $1.44\pm 0.06$ | $34.4\pm 3.1$ | $657\pm 56$ |
            | Poly(DTB suberate) | 37 | $1.24\pm 0.04$ | $31.0\pm 0.8$ | $138\pm 150$ |
            | Poly(DTB sebacate) | 30 | $0.28\pm 0.03$ | $5.8\pm 0.7$ | $744\pm 50$ |
            | Poly(DTO adipate) | 28 | $0.39\pm 0.09$ | $7.6\pm 1.8$ | $676\pm 86$ |
            <!-- STRUCTURE-PROPERTY CORRELATIONS IN COMBINATORIAL LIBRARY 73 -->""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | Poly(DTE succinate) | 78°C |
            | Poly(DTB succinate) | 67°C |
            | Poly(DTE adipate) | 61°C |
            | Poly(DTH succinate) | 53°C |
            | Poly(DTE suberate) | 50°C |
            | Poly(DTO succinate) | 48°C |
            | Poly(DTB adipate) | 46°C |
            | Poly(DTE sebacate) | 44°C |
            | Poly(DTB suberate) | 37°C |
            | Poly(DTB sebacate) | 30°C |
            | Poly(DTO adipate) | 28°C |

            I hope these examples can help you understand the question better. Thank you very much, I hope you can do a good job! 
            A:"""
     
    client = OpenAI(api_key=api_key)
    max_retries = 3 
    retry_wait = 60  
    
    for attempt in range(max_retries):
        try:
            print('get response......')
            response = client.chat.completions.create(
                            model='gpt-5.4',
                            messages=[{
                                "role": "system",
                                "content": """Answer the question as truthfully as possible using the provided context,
                                            and if the answer is not contained within the text below, say "Nan" """
                            },
                                {"role": "user", "content": user_heading + user_ending}]
                        )
            answer_str = response.choices[0].message.content
            polymer_properties_list.append(answer_str)
            print(f"Paper {str(i).zfill(3)} processed successfully.")
            break
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < max_retries - 1:  # Retry if not the last attempt
                print(f"Retrying in {retry_wait} seconds...")
                time.sleep(retry_wait)
            else:
                print("All attempts failed. Returning 'Nan'.")
                polymer_properties_list.append("Nan")

Start to analyze paper301
get response......
Paper 301 processed successfully.
Start to analyze paper302
get response......
Paper 302 processed successfully.
Start to analyze paper303
get response......
Paper 303 processed successfully.
Start to analyze paper304
get response......
Paper 304 processed successfully.
Start to analyze paper305
get response......
Paper 305 processed successfully.
Start to analyze paper306
get response......
Paper 306 processed successfully.
Start to analyze paper307
get response......
Paper 307 processed successfully.
Start to analyze paper308
get response......
Paper 308 processed successfully.
Start to analyze paper309
get response......
Paper 309 processed successfully.
Start to analyze paper310
get response......
Paper 310 processed successfully.
Start to analyze paper311
get response......
Paper 311 processed successfully.
Start to analyze paper312
get response......
Paper 312 processed successfully.
Start to analyze paper313
get response......
Paper 313 processed successfully.
Start to analyze paper314
get response......
Paper 314 processed successfully.
Start to analyze paper315
get response......
Paper 315 processed successfully.
Start to analyze paper316
get response......
Paper 316 processed successfully.
Start to analyze paper317
get response......
Paper 317 processed successfully.
Start to analyze paper318
get response......
Paper 318 processed successfully.
Start to analyze paper319
get response......
Paper 319 processed successfully.
Start to analyze paper320
get response......
Paper 320 processed successfully.
Start to analyze paper321
get response......
Paper 321 processed successfully.
Start to analyze paper322
get response......
Paper 322 processed successfully.
Start to analyze paper323
get response......
Paper 323 processed successfully.
Start to analyze paper324
get response......
Paper 324 processed successfully.
Start to analyze paper325
get response......
Paper 325 processed successfully.
Start to analyze paper326
get response......
Paper 326 processed successfully.
Start to analyze paper327
get response......
Paper 327 processed successfully.
Start to analyze paper328
get response......
Paper 328 processed successfully.
Start to analyze paper329
get response......
Paper 329 processed successfully.
Start to analyze paper330
get response......
Paper 330 processed successfully.
Start to analyze paper331
get response......
Paper 331 processed successfully.
Start to analyze paper332
get response......
Paper 332 processed successfully.
Start to analyze paper333
get response......
Paper 333 processed successfully.
Start to analyze paper334
get response......
Paper 334 processed successfully.
Start to analyze paper335
get response......
Paper 335 processed successfully.
Start to analyze paper336
get response......
Paper 336 processed successfully.
Start to analyze paper337
get response......
Paper 337 processed successfully.
Start to analyze paper338
get response......
Paper 338 processed successfully.
Start to analyze paper339
get response......
Paper 339 processed successfully.
Start to analyze paper340
get response......
Paper 340 processed successfully.
Start to analyze paper341
get response......
Paper 341 processed successfully.
Start to analyze paper342
get response......
Paper 342 processed successfully.
Start to analyze paper343
get response......
Paper 343 processed successfully.
Start to analyze paper344
get response......
Paper 344 processed successfully.
Start to analyze paper345
get response......
Paper 345 processed successfully.
Start to analyze paper346
get response......
Paper 346 processed successfully.
Start to analyze paper347
get response......
Paper 347 processed successfully.
Start to analyze paper348
get response......
Paper 348 processed successfully.
Start to analyze paper349
get response......
Paper 349 processed successfully.
Start to analyze paper350
get response......
Paper 350 processed successfully.
Start to analyze paper351
get response......
Paper 351 processed successfully.
Start to analyze paper352
get response......
Paper 352 processed successfully.
Start to analyze paper353
get response......
Paper 353 processed successfully.
Start to analyze paper354
get response......
Paper 354 processed successfully.
Start to analyze paper355
get response......
Paper 355 processed successfully.
Start to analyze paper356
get response......
Paper 356 processed successfully.
Start to analyze paper357
get response......
Paper 357 processed successfully.
Start to analyze paper358
get response......
Paper 358 processed successfully.
Start to analyze paper359
get response......
Paper 359 processed successfully.
Start to analyze paper360
get response......
Paper 360 processed successfully.
Start to analyze paper361
get response......
Paper 361 processed successfully.
Start to analyze paper362
get response......
Paper 362 processed successfully.
Start to analyze paper363
get response......
Paper 363 processed successfully.
Start to analyze paper364
get response......
Paper 364 processed successfully.
Start to analyze paper365
get response......
Paper 365 processed successfully.
Start to analyze paper366
get response......
Paper 366 processed successfully.
Start to analyze paper367
get response......
Paper 367 processed successfully.
Start to analyze paper368
get response......
Paper 368 processed successfully.
Start to analyze paper369
get response......
Paper 369 processed successfully.
Start to analyze paper370
get response......
Paper 370 processed successfully.
Start to analyze paper371
get response......
Paper 371 processed successfully.
Start to analyze paper372
get response......
Paper 372 processed successfully.
Start to analyze paper373
get response......
Paper 373 processed successfully.
Start to analyze paper374
get response......
Paper 374 processed successfully.
Start to analyze paper375
get response......
Paper 375 processed successfully.
Start to analyze paper376
get response......
Paper 376 processed successfully.
Start to analyze paper377
get response......
Paper 377 processed successfully.
Start to analyze paper378
get response......
Paper 378 processed successfully.
Start to analyze paper379
get response......
Paper 379 processed successfully.
Start to analyze paper380
get response......
Paper 380 processed successfully.
Start to analyze paper381
get response......
Paper 381 processed successfully.
Start to analyze paper382
get response......
Paper 382 processed successfully.
Start to analyze paper383
get response......
Paper 383 processed successfully.
Start to analyze paper384
get response......
Paper 384 processed successfully.
Start to analyze paper385
get response......
Paper 385 processed successfully.
Start to analyze paper386
get response......
Paper 386 processed successfully.
Start to analyze paper387
get response......
Paper 387 processed successfully.
Start to analyze paper388
get response......
Paper 388 processed successfully.
Start to analyze paper389
get response......
Paper 389 processed successfully.
Start to analyze paper390
get response......
Paper 390 processed successfully.
Start to analyze paper391
get response......
Paper 391 processed successfully.
Start to analyze paper392
get response......
Paper 392 processed successfully.
Start to analyze paper393
get response......
Paper 393 processed successfully.
Start to analyze paper394
get response......
Paper 394 processed successfully.
Start to analyze paper395
get response......
Paper 395 processed successfully.
Start to analyze paper396
get response......
Paper 396 processed successfully.
Start to analyze paper397
get response......
Paper 397 processed successfully.
Start to analyze paper398
get response......
Paper 398 processed successfully.
Start to analyze paper399
get response......
Paper 399 processed successfully.
Start to analyze paper400
get response......
Paper 400 processed successfully.
Start to analyze paper401
get response......
Paper 401 processed successfully.
Start to analyze paper402
get response......
Paper 402 processed successfully.
Start to analyze paper403
get response......
Paper 403 processed successfully.
Start to analyze paper404
get response......
Paper 404 processed successfully.
Start to analyze paper405
get response......
Paper 405 processed successfully.
Start to analyze paper406
get response......
Paper 406 processed successfully.
Start to analyze paper407
get response......
Paper 407 processed successfully.
Start to analyze paper408
get response......
Paper 408 processed successfully.
Start to analyze paper409
get response......
Paper 409 processed successfully.
Start to analyze paper410
get response......
Paper 410 processed successfully.
Start to analyze paper411
get response......
Paper 411 processed successfully.
Start to analyze paper412
get response......
Paper 412 processed successfully.
Start to analyze paper413
get response......
Paper 413 processed successfully.
Start to analyze paper414
get response......
Paper 414 processed successfully.
Start to analyze paper415
get response......
Paper 415 processed successfully.
Start to analyze paper416
get response......
Paper 416 processed successfully.
Start to analyze paper417
get response......
Paper 417 processed successfully.
Start to analyze paper418
get response......
Paper 418 processed successfully.
Start to analyze paper419
get response......
Paper 419 processed successfully.
Start to analyze paper420
get response......
Paper 420 processed successfully.
Start to analyze paper421
get response......
Paper 421 processed successfully.
Start to analyze paper422
get response......
Paper 422 processed successfully.
Start to analyze paper423
get response......
Paper 423 processed successfully.
Start to analyze paper424
get response......
Paper 424 processed successfully.
Start to analyze paper425
get response......
Paper 425 processed successfully.
Start to analyze paper426
get response......
Paper 426 processed successfully.
Start to analyze paper427
get response......
Paper 427 processed successfully.
Start to analyze paper428
get response......
Paper 428 processed successfully.
Start to analyze paper429
get response......
Paper 429 processed successfully.
Start to analyze paper430
get response......
Paper 430 processed successfully.
Start to analyze paper431
get response......
Paper 431 processed successfully.
Start to analyze paper432
get response......
Paper 432 processed successfully.
Start to analyze paper433
get response......
Paper 433 processed successfully.
Start to analyze paper434
get response......
Paper 434 processed successfully.
Start to analyze paper435
get response......
Paper 435 processed successfully.
Start to analyze paper436
get response......
Paper 436 processed successfully.
Start to analyze paper437
get response......
Paper 437 processed successfully.
Start to analyze paper438
get response......
Paper 438 processed successfully.
Start to analyze paper439
get response......
Paper 439 processed successfully.
Start to analyze paper440
get response......
Paper 440 processed successfully.
Start to analyze paper441
get response......
Paper 441 processed successfully.
Start to analyze paper442
get response......
Paper 442 processed successfully.
Start to analyze paper443
get response......
Paper 443 processed successfully.
Start to analyze paper444
get response......
Paper 444 processed successfully.
Start to analyze paper445
get response......
Paper 445 processed successfully.
Start to analyze paper446
get response......
Paper 446 processed successfully.
Start to analyze paper447
get response......
Paper 447 processed successfully.
Start to analyze paper448
get response......
Paper 448 processed successfully.
Start to analyze paper449
get response......
Paper 449 processed successfully.
Start to analyze paper450
get response......
Paper 450 processed successfully.
Start to analyze paper451
get response......
Paper 451 processed successfully.
Start to analyze paper452
get response......
Paper 452 processed successfully.
Start to analyze paper453
get response......
Paper 453 processed successfully.
Start to analyze paper454
get response......
Paper 454 processed successfully.
Start to analyze paper455
get response......
Paper 455 processed successfully.
Start to analyze paper456
get response......
Paper 456 processed successfully.
Start to analyze paper457
get response......
Paper 457 processed successfully.
Start to analyze paper458
get response......
Paper 458 processed successfully.
Start to analyze paper459
get response......
Paper 459 processed successfully.
Start to analyze paper460
get response......
Paper 460 processed successfully.
Start to analyze paper461
get response......
Paper 461 processed successfully.
Start to analyze paper462
get response......
Paper 462 processed successfully.
Start to analyze paper463
get response......
Paper 463 processed successfully.
Start to analyze paper464
get response......
Paper 464 processed successfully.
Start to analyze paper465
get response......
Paper 465 processed successfully.
Start to analyze paper466
get response......
Paper 466 processed successfully.
Start to analyze paper467
get response......
Paper 467 processed successfully.
Start to analyze paper468
get response......
Paper 468 processed successfully.
Start to analyze paper469
get response......
Paper 469 processed successfully.
Start to analyze paper470
get response......
Paper 470 processed successfully.
Start to analyze paper471
get response......
Paper 471 processed successfully.
Start to analyze paper472
get response......
Paper 472 processed successfully.
Start to analyze paper473
get response......
Paper 473 processed successfully.
Start to analyze paper474
get response......
Paper 474 processed successfully.
Start to analyze paper475
get response......
Paper 475 processed successfully.
Start to analyze paper476
get response......
Paper 476 processed successfully.
Start to analyze paper477
get response......
Paper 477 processed successfully.
Start to analyze paper478
get response......
Paper 478 processed successfully.
Start to analyze paper479
get response......
Paper 479 processed successfully.
Start to analyze paper480
get response......
Paper 480 processed successfully.
Start to analyze paper481
get response......
Paper 481 processed successfully.
Start to analyze paper482
get response......
Paper 482 processed successfully.
Start to analyze paper483
get response......
Paper 483 processed successfully.
Start to analyze paper484
get response......
Paper 484 processed successfully.
Start to analyze paper485
get response......
Paper 485 processed successfully.
Start to analyze paper486
get response......
Paper 486 processed successfully.
Start to analyze paper487
get response......
Paper 487 processed successfully.
Start to analyze paper488
get response......
Paper 488 processed successfully.
Start to analyze paper489
get response......
Paper 489 processed successfully.
Start to analyze paper490
get response......
Paper 490 processed successfully.
Start to analyze paper491
get response......
Paper 491 processed successfully.
Start to analyze paper492
get response......
Paper 492 processed successfully.
Start to analyze paper493
get response......
Paper 493 processed successfully.
Start to analyze paper494
get response......
Paper 494 processed successfully.
Start to analyze paper495
get response......
Paper 495 processed successfully.
Start to analyze paper496
get response......
Paper 496 processed successfully.
Start to analyze paper497
get response......
Paper 497 processed successfully.
Start to analyze paper498
get response......
Paper 498 processed successfully.
Start to analyze paper499
get response......
Paper 499 processed successfully.
Start to analyze paper500
get response......
Paper 500 processed successfully.
Start to analyze paper501
get response......
Paper 501 processed successfully.
Start to analyze paper502
get response......
Paper 502 processed successfully.
Start to analyze paper503
get response......
Paper 503 processed successfully.
Start to analyze paper504
get response......
Paper 504 processed successfully.
Start to analyze paper505
get response......
Paper 505 processed successfully.
Start to analyze paper506
get response......
Paper 506 processed successfully.
Start to analyze paper507
get response......
Paper 507 processed successfully.
Start to analyze paper508
get response......
Paper 508 processed successfully.
Start to analyze paper509
get response......
Paper 509 processed successfully.
Start to analyze paper510
get response......
Paper 510 processed successfully.
Start to analyze paper511
get response......
Paper 511 processed successfully.
Start to analyze paper512
get response......
Paper 512 processed successfully.
Start to analyze paper513
get response......
Paper 513 processed successfully.
Start to analyze paper514
get response......
Paper 514 processed successfully.
Start to analyze paper515
get response......
Paper 515 processed successfully.
Start to analyze paper516
get response......
Paper 516 processed successfully.
Start to analyze paper517
get response......
Paper 517 processed successfully.
Start to analyze paper518
get response......
Paper 518 processed successfully.
Start to analyze paper519
get response......
Paper 519 processed successfully.
Start to analyze paper520
get response......
Paper 520 processed successfully.
Start to analyze paper521
get response......
Paper 521 processed successfully.
Start to analyze paper522
get response......
Paper 522 processed successfully.
Start to analyze paper523
get response......
Paper 523 processed successfully.
Start to analyze paper524
get response......
Paper 524 processed successfully.
Start to analyze paper525
get response......
Paper 525 processed successfully.
Start to analyze paper526
get response......
Paper 526 processed successfully.
Start to analyze paper527
get response......
Paper 527 processed successfully.
Start to analyze paper528
get response......
Paper 528 processed successfully.
Start to analyze paper529
get response......
Paper 529 processed successfully.
Start to analyze paper530
get response......
Paper 530 processed successfully.
Start to analyze paper531
get response......
Paper 531 processed successfully.
Start to analyze paper532
get response......
Paper 532 processed successfully.
Start to analyze paper533
get response......
Paper 533 processed successfully.
Start to analyze paper534
get response......
Paper 534 processed successfully.
Start to analyze paper535
get response......
Paper 535 processed successfully.
Start to analyze paper536
get response......
Paper 536 processed successfully.
Start to analyze paper537
get response......
Paper 537 processed successfully.
Start to analyze paper538
get response......
Paper 538 processed successfully.
Start to analyze paper539
get response......
Paper 539 processed successfully.
Start to analyze paper540
get response......
Paper 540 processed successfully.
Start to analyze paper541
get response......
Paper 541 processed successfully.
Start to analyze paper542
get response......
Paper 542 processed successfully.
Start to analyze paper543
get response......
Paper 543 processed successfully.
Start to analyze paper544
get response......
Paper 544 processed successfully.
Start to analyze paper545
get response......
Paper 545 processed successfully.
Start to analyze paper546
get response......
Paper 546 processed successfully.
Start to analyze paper547
get response......
Paper 547 processed successfully.
Start to analyze paper548
get response......
Paper 548 processed successfully.
Start to analyze paper549
get response......
Paper 549 processed successfully.
Start to analyze paper550
get response......
Paper 550 processed successfully.
Start to analyze paper551
get response......
Paper 551 processed successfully.
Start to analyze paper552
get response......
Paper 552 processed successfully.
Start to analyze paper553
get response......
Paper 553 processed successfully.

In [26]:
print(polymer_properties_list[80])

| Polyamide name | Glass transition temperature |
|---|---|
| poly(m-xylene adipamide) (MXD6) | 85°C |

In [27]:
# import pickle
# with open('polymer_properties_list_gpt_5(001_050).pkl', 'wb') as f:
#     pickle.dump(polymer_properties_list, f)

import pickle
with open('polymer_properties_list_gpt_54(301_580).pkl', 'wb') as f:
    pickle.dump(polymer_properties_list, f)

In [30]:
with open('polymer_properties_list_gpt_54(001_100).pkl', 'rb') as f:
    loaded_list_0_100 = pickle.load(f)

with open('polymer_properties_list_gpt_54(100_300).pkl', 'rb') as f:
    loaded_list_100_300 = pickle.load(f)

In [31]:
import io
import re
import pandas as pd

all_dataframes = []

for index, answer_str in enumerate(loaded_list_0_100, start=1):
    # 改进后的正则：允许最后一行无换行
    table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
    if table_match:
        table_str = table_match[0]

        # 去掉每行两边的 |，避免 read_csv 产生空列
        table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

        data_io = io.StringIO(table_str)
        try:
            df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
            df.columns = df.columns.str.strip()
            df = df.dropna(how="all")
            df = df.reset_index(drop=True)
            df["ID"] = index
            all_dataframes.append(df)
        except Exception as e:
            print(f"Error parsing entry {index}: {e}")
    else:
        print(f"No table found in entry {index}")

combined_df_0_100 = pd.concat(all_dataframes, ignore_index=True)

In [33]:
import io
import re
import pandas as pd

all_dataframes = []

for index, answer_str in enumerate(loaded_list_100_300, start=101):
    # 改进后的正则：允许最后一行无换行
    table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
    if table_match:
        table_str = table_match[0]

        # 去掉每行两边的 |，避免 read_csv 产生空列
        table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

        data_io = io.StringIO(table_str)
        try:
            df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
            df.columns = df.columns.str.strip()
            df = df.dropna(how="all")
            df = df.reset_index(drop=True)
            df["ID"] = index
            all_dataframes.append(df)
        except Exception as e:
            print(f"Error parsing entry {index}: {e}")
    else:
        print(f"No table found in entry {index}")

combined_df_101_300 = pd.concat(all_dataframes, ignore_index=True)

In [28]:
import io
import re
import pandas as pd

all_dataframes = []

for index, answer_str in enumerate(polymer_properties_list, start=301):
    # 改进后的正则：允许最后一行无换行
    table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
    if table_match:
        table_str = table_match[0]

        # 去掉每行两边的 |，避免 read_csv 产生空列
        table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

        data_io = io.StringIO(table_str)
        try:
            df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
            df.columns = df.columns.str.strip()
            df = df.dropna(how="all")
            df = df.reset_index(drop=True)
            df["ID"] = index
            all_dataframes.append(df)
        except Exception as e:
            print(f"Error parsing entry {index}: {e}")
    else:
        print(f"No table found in entry {index}")

combined_df = pd.concat(all_dataframes, ignore_index=True)

In [34]:
combined_df_final=pd.concat([combined_df_0_100, combined_df_101_300, combined_df], ignore_index=True)

In [37]:
combined_df_final[combined_df_final['ID'] == 79]

    Polyamide name Glass transition temperature  ID
524            PA                          Nan   79
525           PA'                        232°C   79

In [38]:
combined_df_final = combined_df_final[~combined_df_final.apply(lambda row: row.astype(str).str.contains('---').any(), axis=1)]
df_cleaned = combined_df_final[~combined_df_final.apply(lambda row: row.astype(str).str.contains('--').any(), axis=1)]

In [ ]:
# df_cleaned_with_KC = combined_df_final[~combined_df_final.apply(lambda row: row.astype(str).str.contains('--').any(), axis=1)]
# def find_rows_with_K(df, col):
#     mask = df[col].astype(str).str.contains("K", na=False)
#     return df[mask].copy()
# df_K = find_rows_with_K(df_cleaned_with_KC, "Glass transition temperature")

In [ ]:
#df_K.to_excel(r'D:\AI4polymer\PA_design\reference\get_real_label\gpt54_Tg_with_K.xlsx', index=False)

In [39]:
def remove_temp_unit(x):
    try:
        if 'K' in str(x):
            return float(str(x).replace('K', ''))
        elif '°C' in str(x):
            return float(str(x).replace('°C', ''))
        else:
            return x
    except ValueError:
        return x

df_cleaned['Glass transition temperature'] = df_cleaned['Glass transition temperature'].apply(remove_temp_unit)

In [40]:
df_cleaned=df_cleaned.reset_index(drop=True)
df_cleaned

     Polyamide name Glass transition temperature   ID
0               Va                         258.0    1
1               Vb                         262.0    1
2               Vi                         256.0    1
3              VIa                         258.0    1
4              VIc                         270.0    1
...             ...                          ...  ...
2554         PA 46                          78.0  578
2555         PA 66                          65.0  578
2556          PA 6                          58.0  578
2557          PA 6                         315.3  579
2558       Nylon 6                          Nan   580

[2559 rows x 3 columns]

In [ ]:
#df_cleaned.to_excel('PA_gpt_54_extraction.xlsx', index=False)

### GPT 5.4 mini

In [ ]:
from openai import OpenAI
api_key = 'xxxxxxxx' # Replace 'xxxxxxxx' with your actual OpenAI API key

In [11]:
import pandas as pd
import os
import time
polymer_properties_list = []
for i in range(1, 581):
    file_path = os.path.join(r'D:\AI4polymer\PA_design\reference\all_clean_md_files', f'{str(i).zfill(3)}.md')
    print("Start to analyze paper" + str(i).zfill(3))
    with open(file_path, 'r', encoding='utf-8') as f:
        text=f.read()
    user_heading = text
    user_ending = """ Q: Can you summarize the following details of polyamide(PA) in a table: 
            Polyamide name, Glass transition temperature? 
            If any information is not provided or you are unsure, use "Nan". 
            Guidelines:
            1. For the Glass transition temperature (Tg), the format is xxxK or xxx°C.
            2. There may be many different polyamides in an article, so please don't leave them out and use multiple rows to express.
            3. Sometimes the polymers' names seems like nan-polyamides, but they are actually polyamides(e.g. some polyesters, polyarylates ... also contain amide bonds, and are therefore considered polyamides.), please be careful to identify them.
            4. Please only focus on the polyamide homopolymer information, don't include polyamide copolymers.
            5.  **Only output** the Markdown table. Do not include any other text, explanations, or comments. The table must start with the header: `| Polyamide name | Glass transition temperature |`.

            The table should have 2 columns:
            |Polyamide name |Glass transition temperature|

            To help you understand the question, here are some examples:
            Example 1:
            Input:""Polyamides **P4,** **P6,** **P8,** **P10,and** **P12** were syn-thesized by interfacial polycondensation $\mathrm {n}^{6}$ of
                    **Table II Thermal Properties of Polyamides**
                    | Polymer | $T_{g}{}^{\mathrm {a}}\left({}^{\circ }\mathrm {C}\right)$ | $T_{d}{}^{\mathrm {c}}\left({}^{\circ }\mathrm {C}\right)$ |
                    | --- | --- | --- |
                    | P4 | b | 451 |
                    | P6 | 201 | 458 |
                    | P8 | 185 | 459 |
                    | P10 | 166 | 459 |
                    | P12 | 154 | 461 |
                    "Glass transition temperature, observed by DSC in a ni-trogen atmosphere.
                    bNot observed.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | P4 | Nan |
            | P6 | 201°C |
            | P8 | 185°C |
            | P10 | 166°C |
            | P12 | 154°C |

            Example 2:
            Input:"" <!-- PAI GAS TRANSPORT PROPERTIES 2185 -->
                    Table II.Structural and Physical Parameters of $\text {PAIs}^{\mathrm {a}}$ 
                    | Sample | $\begin{array}{c}T_{g}\\ (\mathrm {\sim K})\end{array}$ | r<br>$\left(\mathrm {kg}/\mathrm {m}^{3}\right)$ | $<p>$(nm) | $\left\langle d_{0}\right\rangle$(nm) | FFV | $E_{\mathrm {coh}}$(kJ/mol) |
                    | --- | --- | --- | --- | --- | --- | --- |
                    | PAI(TMI/DPA) | 540 | 1.3012 | 1.18 | 0.55 | 0.1278 | 198.63 |
                    | PAI(TMI/HEA) | 510 | 1.3205 | 1.04 | 0.53 | 0.1298 | 232.33 |
                    | PAI(TMI/TFA) | 527 | 1.4301 | 1.06 | 0.52 | 0.1459 | 273.09 |
                    | PAI(TMI/CDA) | 618 | 1.2581 | 1.60 | 0.60 | 0.1499 | 259.04 |
                    | PAI(PMI/CDA) | 623 | 1.2864 | 1.15 | 0.62 | 0.1551 | 281.23 |
                    a glass transition temperature; $ρ,$  density ( $\left.T=23^{\circ }\mathrm {C}\right);$  ^p&, persistence length; $\left\langle d_{0}\right\rangle ,$  inter-chain distance; FFV, fractional free $T_{g},$ volume $\left(T=23^{\circ }\mathrm {C}\right);E_{\mathrm {coh}}$  molar cohesive energy density.""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | PAI(TMI/DPA) | 540K |
            | PAI(TMI/HEA) | 510K |
            | PAI(TMI/TFA) | 527K |
            | PAI(TMI/CDA) | 618K |
            | PAI(PMI/CDA) | 623K |

            Example 3:
            input:"" The diphenolic monomers were prepared using minor modifications of previously published procedures.11 Briefly, each tyrosine alkyl ester was coupled with recrystallized
            3-(4-hydroxyphenyl)-propionic acid (or in some cases, 4-hydroxyphenylacetic acid) using EDCI (1.0 eq.) and HOBt(0.1 eq.) in a solution of either N-methylpyrrolidinone:ethyl
            acetate (1:3; 1.5M concentration of tyrosine ester) or aceto-nitrile (0.75M concentration of tyrosine ester). After aqueousworkup, rotoevaporation, and trituration in hexane, the di-
            phenolic monomers (Figs. 1 and 2) were obtained in puritiesof 96–99% [as measured by high power liquid chromatog- raphy (HPLC) peak ratios or by melting point depressionusing DSC]. Most of the diacids were commercially available in high purity and were recrystallized prior to useFibroblast proliferation was observed to be more sensitive to the chemical structure of the polymer than
            TABLE I
            Room Temperature ( $\left(22^{\circ }\mathrm {C}\right)$  Mechanical Properties of Selected Polyarylates
            | Polymer | $\mathrm {T}_{g}\left({}^{\circ }\mathrm {C}\right)$ | Young’s Modulus (GPa) | Yield Stress (MPa) | Strain at Break (%) |
            | --- | --- | --- | --- | --- |
            | Poly(DTE succinate) | 78 | $1.68\pm 0.17$ | $40.7\pm 3.2$ | $304\pm 102$ |
            | Poly(DTB succinate) | 67 | $1.56\pm 0.18$ | $44.8\pm 3.8$ | $566\pm 36$ |
            | Poly(DTE adipate) | 61 | $1.56\pm 0.10$ | $42.0\pm 4.4$ | $638\pm 152$ |
            | Poly(DTH succinate) | 53 | $1.61\pm 0.10$ | $44.8\pm 2.3$ | $456\pm 103$ |
            | Poly(DTE suberate) | 50 | $1.39\pm 0.10$ | $39.9\pm 3.7$ | $534\pm 91$ |
            | Poly(DTO succinate) | 48 | $1.41\pm 0.18$ | $41.9\pm 4.5$ | $622\pm 68$ |
            | Poly(DTB adipate) | 46 | $1.49\pm 0.22$ | $40.5\pm 3.5$ | $710\pm 96$ |
            | Poly(DTE sebacate) | 44 | $1.44\pm 0.06$ | $34.4\pm 3.1$ | $657\pm 56$ |
            | Poly(DTB suberate) | 37 | $1.24\pm 0.04$ | $31.0\pm 0.8$ | $138\pm 150$ |
            | Poly(DTB sebacate) | 30 | $0.28\pm 0.03$ | $5.8\pm 0.7$ | $744\pm 50$ |
            | Poly(DTO adipate) | 28 | $0.39\pm 0.09$ | $7.6\pm 1.8$ | $676\pm 86$ |
            <!-- STRUCTURE-PROPERTY CORRELATIONS IN COMBINATORIAL LIBRARY 73 -->""
            
            Output should be:
            |Polyamide name |Glass transition temperature|
            | Poly(DTE succinate) | 78°C |
            | Poly(DTB succinate) | 67°C |
            | Poly(DTE adipate) | 61°C |
            | Poly(DTH succinate) | 53°C |
            | Poly(DTE suberate) | 50°C |
            | Poly(DTO succinate) | 48°C |
            | Poly(DTB adipate) | 46°C |
            | Poly(DTE sebacate) | 44°C |
            | Poly(DTB suberate) | 37°C |
            | Poly(DTB sebacate) | 30°C |
            | Poly(DTO adipate) | 28°C |

            I hope these examples can help you understand the question better. Thank you very much, I hope you can do a good job! 
            A:"""
     
    client = OpenAI(api_key=api_key)
    max_retries = 3 
    retry_wait = 60  
    
    for attempt in range(max_retries):
        try:
            print('get response......')
            response = client.chat.completions.create(
                            model='gpt-5.4-mini',
                            messages=[{
                                "role": "system",
                                "content": """Answer the question as truthfully as possible using the provided context,
                                            and if the answer is not contained within the text below, say "Nan" """
                            },
                                {"role": "user", "content": user_heading + user_ending}]
                        )
            answer_str = response.choices[0].message.content
            polymer_properties_list.append(answer_str)
            print(f"Paper {str(i).zfill(3)} processed successfully.")
            break
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < max_retries - 1:  # Retry if not the last attempt
                print(f"Retrying in {retry_wait} seconds...")
                time.sleep(retry_wait)
            else:
                print("All attempts failed. Returning 'Nan'.")
                polymer_properties_list.append("Nan")

Start to analyze paper001
get response......
Paper 001 processed successfully.
Start to analyze paper002
get response......
Paper 002 processed successfully.
Start to analyze paper003
get response......
Paper 003 processed successfully.
Start to analyze paper004
get response......
Paper 004 processed successfully.
Start to analyze paper005
get response......
Paper 005 processed successfully.
Start to analyze paper006
get response......
Paper 006 processed successfully.
Start to analyze paper007
get response......
Paper 007 processed successfully.
Start to analyze paper008
get response......
Paper 008 processed successfully.
Start to analyze paper009
get response......
Paper 009 processed successfully.
Start to analyze paper010
get response......
Paper 010 processed successfully.
Start to analyze paper011
get response......
Paper 011 processed successfully.
Start to analyze paper012
get response......
Paper 012 processed successfully.
Start to analyze paper013
get response......
Paper 013 processed successfully.
Start to analyze paper014
get response......
Paper 014 processed successfully.
Start to analyze paper015
get response......
Paper 015 processed successfully.
Start to analyze paper016
get response......
Paper 016 processed successfully.
Start to analyze paper017
get response......
Paper 017 processed successfully.
Start to analyze paper018
get response......
Paper 018 processed successfully.
Start to analyze paper019
get response......
Paper 019 processed successfully.
Start to analyze paper020
get response......
Paper 020 processed successfully.
Start to analyze paper021
get response......
Paper 021 processed successfully.
Start to analyze paper022
get response......
Paper 022 processed successfully.
Start to analyze paper023
get response......
Paper 023 processed successfully.
Start to analyze paper024
get response......
Paper 024 processed successfully.
Start to analyze paper025
get response......
Paper 025 processed successfully.
Start to analyze paper026
get response......
Paper 026 processed successfully.
Start to analyze paper027
get response......
Paper 027 processed successfully.
Start to analyze paper028
get response......
Paper 028 processed successfully.
Start to analyze paper029
get response......
Paper 029 processed successfully.
Start to analyze paper030
get response......
Paper 030 processed successfully.
Start to analyze paper031
get response......
Paper 031 processed successfully.
Start to analyze paper032
get response......
Paper 032 processed successfully.
Start to analyze paper033
get response......
Paper 033 processed successfully.
Start to analyze paper034
get response......
Paper 034 processed successfully.
Start to analyze paper035
get response......
Paper 035 processed successfully.
Start to analyze paper036
get response......
Paper 036 processed successfully.
Start to analyze paper037
get response......
Paper 037 processed successfully.
Start to analyze paper038
get response......
Paper 038 processed successfully.
Start to analyze paper039
get response......
Paper 039 processed successfully.
Start to analyze paper040
get response......
Paper 040 processed successfully.
Start to analyze paper041
get response......
Paper 041 processed successfully.
Start to analyze paper042
get response......
Paper 042 processed successfully.
Start to analyze paper043
get response......
Paper 043 processed successfully.
Start to analyze paper044
get response......
Paper 044 processed successfully.
Start to analyze paper045
get response......
Paper 045 processed successfully.
Start to analyze paper046
get response......
Paper 046 processed successfully.
Start to analyze paper047
get response......
Paper 047 processed successfully.
Start to analyze paper048
get response......
Paper 048 processed successfully.
Start to analyze paper049
get response......
Paper 049 processed successfully.
Start to analyze paper050
get response......
Paper 050 processed successfully.
Start to analyze paper051
get response......
Paper 051 processed successfully.
Start to analyze paper052
get response......
Paper 052 processed successfully.
Start to analyze paper053
get response......
Paper 053 processed successfully.
Start to analyze paper054
get response......
Paper 054 processed successfully.
Start to analyze paper055
get response......
Paper 055 processed successfully.
Start to analyze paper056
get response......
Paper 056 processed successfully.
Start to analyze paper057
get response......
Paper 057 processed successfully.
Start to analyze paper058
get response......
Paper 058 processed successfully.
Start to analyze paper059
get response......
Paper 059 processed successfully.
Start to analyze paper060
get response......
Paper 060 processed successfully.
Start to analyze paper061
get response......
Paper 061 processed successfully.
Start to analyze paper062
get response......
Paper 062 processed successfully.
Start to analyze paper063
get response......
Paper 063 processed successfully.
Start to analyze paper064
get response......
Paper 064 processed successfully.
Start to analyze paper065
get response......
Paper 065 processed successfully.
Start to analyze paper066
get response......
Paper 066 processed successfully.
Start to analyze paper067
get response......
Paper 067 processed successfully.
Start to analyze paper068
get response......
Paper 068 processed successfully.
Start to analyze paper069
get response......
Paper 069 processed successfully.
Start to analyze paper070
get response......
Paper 070 processed successfully.
Start to analyze paper071
get response......
Paper 071 processed successfully.
Start to analyze paper072
get response......
Paper 072 processed successfully.
Start to analyze paper073
get response......
Paper 073 processed successfully.
Start to analyze paper074
get response......
Paper 074 processed successfully.
Start to analyze paper075
get response......
Paper 075 processed successfully.
Start to analyze paper076
get response......
Paper 076 processed successfully.
Start to analyze paper077
get response......
Paper 077 processed successfully.
Start to analyze paper078
get response......
Paper 078 processed successfully.
Start to analyze paper079
get response......
Paper 079 processed successfully.
Start to analyze paper080
get response......
Paper 080 processed successfully.
Start to analyze paper081
get response......
Paper 081 processed successfully.
Start to analyze paper082
get response......
Paper 082 processed successfully.
Start to analyze paper083
get response......
Paper 083 processed successfully.
Start to analyze paper084
get response......
Paper 084 processed successfully.
Start to analyze paper085
get response......
Paper 085 processed successfully.
Start to analyze paper086
get response......
Paper 086 processed successfully.
Start to analyze paper087
get response......
Paper 087 processed successfully.
Start to analyze paper088
get response......
Paper 088 processed successfully.
Start to analyze paper089
get response......
Paper 089 processed successfully.
Start to analyze paper090
get response......
Paper 090 processed successfully.
Start to analyze paper091
get response......
Paper 091 processed successfully.
Start to analyze paper092
get response......
Paper 092 processed successfully.
Start to analyze paper093
get response......
Paper 093 processed successfully.
Start to analyze paper094
get response......
Paper 094 processed successfully.
Start to analyze paper095
get response......
Paper 095 processed successfully.
Start to analyze paper096
get response......
Paper 096 processed successfully.
Start to analyze paper097
get response......
Paper 097 processed successfully.
Start to analyze paper098
get response......
Paper 098 processed successfully.
Start to analyze paper099
get response......
Paper 099 processed successfully.
Start to analyze paper100
get response......
Paper 100 processed successfully.
Start to analyze paper101
get response......
Paper 101 processed successfully.
Start to analyze paper102
get response......
Paper 102 processed successfully.
Start to analyze paper103
get response......
Paper 103 processed successfully.
Start to analyze paper104
get response......
Paper 104 processed successfully.
Start to analyze paper105
get response......
Paper 105 processed successfully.
Start to analyze paper106
get response......
Paper 106 processed successfully.
Start to analyze paper107
get response......
Paper 107 processed successfully.
Start to analyze paper108
get response......
Paper 108 processed successfully.
Start to analyze paper109
get response......
Paper 109 processed successfully.
Start to analyze paper110
get response......
Paper 110 processed successfully.
Start to analyze paper111
get response......
Paper 111 processed successfully.
Start to analyze paper112
get response......
Paper 112 processed successfully.
Start to analyze paper113
get response......
Paper 113 processed successfully.
Start to analyze paper114
get response......
Paper 114 processed successfully.
Start to analyze paper115
get response......
Paper 115 processed successfully.
Start to analyze paper116
get response......
Paper 116 processed successfully.
Start to analyze paper117
get response......
Paper 117 processed successfully.
Start to analyze paper118
get response......
Paper 118 processed successfully.
Start to analyze paper119
get response......
Paper 119 processed successfully.
Start to analyze paper120
get response......
Paper 120 processed successfully.
Start to analyze paper121
get response......
Paper 121 processed successfully.
Start to analyze paper122
get response......
Paper 122 processed successfully.
Start to analyze paper123
get response......
Paper 123 processed successfully.
Start to analyze paper124
get response......
Paper 124 processed successfully.
Start to analyze paper125
get response......
Paper 125 processed successfully.
Start to analyze paper126
get response......
Paper 126 processed successfully.
Start to analyze paper127
get response......
Paper 127 processed successfully.
Start to analyze paper128
get response......
Paper 128 processed successfully.
Start to analyze paper129
get response......
Paper 129 processed successfully.
Start to analyze paper130
get response......
Paper 130 processed successfully.
Start to analyze paper131
get response......
Paper 131 processed successfully.
Start to analyze paper132
get response......
Paper 132 processed successfully.
Start to analyze paper133
get response......
Paper 133 processed successfully.
Start to analyze paper134
get response......
Paper 134 processed successfully.
Start to analyze paper135
get response......
Paper 135 processed successfully.
Start to analyze paper136
get response......
Paper 136 processed successfully.
Start to analyze paper137
get response......
Paper 137 processed successfully.
Start to analyze paper138
get response......
Paper 138 processed successfully.
Start to analyze paper139
get response......
Paper 139 processed successfully.
Start to analyze paper140
get response......
Paper 140 processed successfully.
Start to analyze paper141
get response......
Paper 141 processed successfully.
Start to analyze paper142
get response......
Paper 142 processed successfully.
Start to analyze paper143
get response......
Paper 143 processed successfully.
Start to analyze paper144
get response......
Paper 144 processed successfully.
Start to analyze paper145
get response......
Paper 145 processed successfully.
Start to analyze paper146
get response......
Paper 146 processed successfully.
Start to analyze paper147
get response......
Paper 147 processed successfully.
Start to analyze paper148
get response......
Paper 148 processed successfully.
Start to analyze paper149
get response......
Paper 149 processed successfully.
Start to analyze paper150
get response......
Paper 150 processed successfully.
Start to analyze paper151
get response......
Paper 151 processed successfully.
Start to analyze paper152
get response......
Paper 152 processed successfully.
Start to analyze paper153
get response......
Paper 153 processed successfully.
Start to analyze paper154
get response......
Paper 154 processed successfully.
Start to analyze paper155
get response......
Paper 155 processed successfully.
Start to analyze paper156
get response......
Paper 156 processed successfully.
Start to analyze paper157
get response......
Paper 157 processed successfully.
Start to analyze paper158
get response......
Paper 158 processed successfully.
Start to analyze paper159
get response......
Paper 159 processed successfully.
Start to analyze paper160
get response......
Paper 160 processed successfully.
Start to analyze paper161
get response......
Paper 161 processed successfully.
Start to analyze paper162
get response......
Paper 162 processed successfully.
Start to analyze paper163
get response......
Paper 163 processed successfully.
Start to analyze paper164
get response......
Paper 164 processed successfully.
Start to analyze paper165
get response......
Paper 165 processed successfully.
Start to analyze paper166
get response......
Paper 166 processed successfully.
Start to analyze paper167
get response......
Paper 167 processed successfully.
Start to analyze paper168
get response......
Paper 168 processed successfully.
Start to analyze paper169
get response......
Paper 169 processed successfully.
Start to analyze paper170
get response......
Paper 170 processed successfully.
Start to analyze paper171
get response......
Paper 171 processed successfully.
Start to analyze paper172
get response......
Paper 172 processed successfully.
Start to analyze paper173
get response......
Paper 173 processed successfully.
Start to analyze paper174
get response......
Paper 174 processed successfully.
Start to analyze paper175
get response......
Paper 175 processed successfully.
Start to analyze paper176
get response......
Paper 176 processed successfully.
Start to analyze paper177
get response......
Paper 177 processed successfully.
Start to analyze paper178
get response......
Paper 178 processed successfully.
Start to analyze paper179
get response......
Paper 179 processed successfully.
Start to analyze paper180
get response......
Paper 180 processed successfully.
Start to analyze paper181
get response......
Paper 181 processed successfully.
Start to analyze paper182
get response......
Paper 182 processed successfully.
Start to analyze paper183
get response......
Paper 183 processed successfully.
Start to analyze paper184
get response......
Paper 184 processed successfully.
Start to analyze paper185
get response......
Paper 185 processed successfully.
Start to analyze paper186
get response......
Paper 186 processed successfully.
Start to analyze paper187
get response......
Paper 187 processed successfully.
Start to analyze paper188
get response......
Paper 188 processed successfully.
Start to analyze paper189
get response......
Paper 189 processed successfully.
Start to analyze paper190
get response......
Paper 190 processed successfully.
Start to analyze paper191
get response......
Paper 191 processed successfully.
Start to analyze paper192
get response......
Paper 192 processed successfully.
Start to analyze paper193
get response......
Paper 193 processed successfully.
Start to analyze paper194
get response......
Paper 194 processed successfully.
Start to analyze paper195
get response......
Paper 195 processed successfully.
Start to analyze paper196
get response......
Paper 196 processed successfully.
Start to analyze paper197
get response......
Paper 197 processed successfully.
Start to analyze paper198
get response......
Paper 198 processed successfully.
Start to analyze paper199
get response......
Paper 199 processed successfully.
Start to analyze paper200
get response......
Paper 200 processed successfully.
Start to analyze paper201
get response......
Paper 201 processed successfully.
Start to analyze paper202
get response......
Paper 202 processed successfully.
Start to analyze paper203
get response......
Paper 203 processed successfully.
Start to analyze paper204
get response......
Paper 204 processed successfully.
Start to analyze paper205
get response......
Paper 205 processed successfully.
Start to analyze paper206
get response......
Paper 206 processed successfully.
Start to analyze paper207
get response......
Paper 207 processed successfully.
Start to analyze paper208
get response......
Paper 208 processed successfully.
Start to analyze paper209
get response......
Paper 209 processed successfully.
Start to analyze paper210
get response......
Paper 210 processed successfully.
Start to analyze paper211
get response......
Paper 211 processed successfully.
Start to analyze paper212
get response......
Paper 212 processed successfully.
Start to analyze paper213
get response......
Paper 213 processed successfully.
Start to analyze paper214
get response......
Paper 214 processed successfully.
Start to analyze paper215
get response......
Paper 215 processed successfully.
Start to analyze paper216
get response......
Paper 216 processed successfully.
Start to analyze paper217
get response......
Paper 217 processed successfully.
Start to analyze paper218
get response......
Paper 218 processed successfully.
Start to analyze paper219
get response......
Paper 219 processed successfully.
Start to analyze paper220
get response......
Paper 220 processed successfully.
Start to analyze paper221
get response......
Paper 221 processed successfully.
Start to analyze paper222
get response......
Paper 222 processed successfully.
Start to analyze paper223
get response......
Paper 223 processed successfully.
Start to analyze paper224
get response......
Paper 224 processed successfully.
Start to analyze paper225
get response......
Paper 225 processed successfully.
Start to analyze paper226
get response......
Paper 226 processed successfully.
Start to analyze paper227
get response......
Paper 227 processed successfully.
Start to analyze paper228
get response......
Paper 228 processed successfully.
Start to analyze paper229
get response......
Paper 229 processed successfully.
Start to analyze paper230
get response......
Paper 230 processed successfully.
Start to analyze paper231
get response......
Paper 231 processed successfully.
Start to analyze paper232
get response......
Paper 232 processed successfully.
Start to analyze paper233
get response......
Paper 233 processed successfully.
Start to analyze paper234
get response......
Paper 234 processed successfully.
Start to analyze paper235
get response......
Paper 235 processed successfully.
Start to analyze paper236
get response......
Paper 236 processed successfully.
Start to analyze paper237
get response......
Paper 237 processed successfully.
Start to analyze paper238
get response......
Paper 238 processed successfully.
Start to analyze paper239
get response......
Paper 239 processed successfully.
Start to analyze paper240
get response......
Paper 240 processed successfully.
Start to analyze paper241
get response......
Paper 241 processed successfully.
Start to analyze paper242
get response......
Paper 242 processed successfully.
Start to analyze paper243
get response......
Paper 243 processed successfully.
Start to analyze paper244
get response......
Paper 244 processed successfully.
Start to analyze paper245
get response......
Paper 245 processed successfully.
Start to analyze paper246
get response......
Paper 246 processed successfully.
Start to analyze paper247
get response......
Paper 247 processed successfully.
Start to analyze paper248
get response......
Paper 248 processed successfully.
Start to analyze paper249
get response......
Paper 249 processed successfully.
Start to analyze paper250
get response......
Paper 250 processed successfully.
Start to analyze paper251
get response......
Paper 251 processed successfully.
Start to analyze paper252
get response......
Paper 252 processed successfully.
Start to analyze paper253
get response......
Paper 253 processed successfully.

In [12]:
import pickle
with open('polymer_properties_list_gpt54mini(1_580).pkl', 'wb') as f:
    pickle.dump(polymer_properties_list, f)

In [13]:
import io
import re
import pandas as pd

def parse_loaded_list_to_df(loaded_list, start_id):
    all_dataframes = []

    for index, answer_str in enumerate(loaded_list, start=start_id):
        # 改进后的正则：允许最后一行无换行
        table_match = re.findall(r"(?:\|.*?\|\s*(?:\n|$))+", answer_str)
        if table_match:
            table_str = table_match[0]

            # 去掉每行两边的 |，避免 read_csv 产生空列
            table_str = "\n".join([line.strip("|") for line in table_str.strip().splitlines()])

            data_io = io.StringIO(table_str)
            try:
                df = pd.read_csv(data_io, sep="|", skipinitialspace=True, on_bad_lines="warn")
                df.columns = df.columns.str.strip()
                df = df.dropna(how="all")
                df = df.reset_index(drop=True)
                df["ID"] = index
                all_dataframes.append(df)
            except Exception as e:
                print(f"Error parsing entry {index}: {e}")
        else:
            print(f"No table found in entry {index}")

    combined_df = pd.concat(all_dataframes, ignore_index=True)

    return combined_df

df_gpt54mini_0_580 = parse_loaded_list_to_df(
    polymer_properties_list,
    start_id=1
)

In [14]:
df_gpt54mini_0_580 = df_gpt54mini_0_580[~df_gpt54mini_0_580.apply(lambda row: row.astype(str).str.contains('---').any(), axis=1)]
df_cleaned = df_gpt54mini_0_580[~df_gpt54mini_0_580.apply(lambda row: row.astype(str).str.contains('--').any(), axis=1)]
def remove_temp_unit(x):
    try:
        if 'K' in str(x):
            return float(str(x).replace('K', ''))
        elif '°C' in str(x):
            return float(str(x).replace('°C', ''))
        else:
            return x
    except ValueError:
        return x

df_cleaned['Glass transition temperature'] = df_cleaned['Glass transition temperature'].apply(remove_temp_unit)
df_cleaned=df_cleaned.reset_index(drop=True)
df_cleaned

     Polyamide name Glass transition temperature   ID
0               Va                         258.0    1
1               Vb                         262.0    1
2               Vi                         256.0    1
3              VIa                         258.0    1
4              VIc                         270.0    1
...             ...                          ...  ...
2537         PA 46                          78.0  578
2538         PA 66                          65.0  578
2539          PA 6                          58.0  578
2540          PA 6                         315.3  579
2541       Nylon 6                          Nan   580

[2542 rows x 3 columns]

In [15]:
df_cleaned.to_excel('PA_gpt54mini_extraction.xlsx', index=False)